[I 16:46:39.631 NotebookApp] Writing notebook server cookie secret to /home/jovyan/.local/share/jupyter/runtime/notebook_cookie_secret
[W 2021-05-16 16:46:40.958 LabApp] 'ip' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2021-05-16 16:46:40.959 LabApp] 'port' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2021-05-16 16:46:40.959 LabApp] 'base_url' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2021-05-16 16:46:40.959 LabApp] 'token' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2021-05-16 16:46:40.959 LabApp] 'trust_xheaders' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2021-05-16 16:46:40.959 LabApp] 'allow_origin' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2021-05-16 16:46:40.959 LabApp] 'allow_origin_pat' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2021-05-16 16:46:40.959 LabApp] 'extra_template_paths' was found in both NotebookApp and ServerApp. This is likely a recent change. This config will only be set in NotebookApp. Please check if you should also config these traits in ServerApp for your purpose.
[W 2021-05-16 16:46:40.959 LabApp] 'jinja_template_vars' was found in both NotebookApp and ServerApp. This is likely a recent change. This config will only be set in NotebookApp. Please check if you should also config these traits in ServerApp for your purpose.
[W 2021-05-16 16:46:40.959 LabApp] 'shutdown_no_activity_timeout' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2021-05-16 16:46:40.959 LabApp] 'tornado_settings' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2021-05-16 16:46:40.959 LabApp] 'tornado_settings' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[I 2021-05-16 16:46:40.973 LabApp] JupyterLab extension loaded from /srv/conda/envs/notebook/lib/python3.7/site-packages/jupyterlab
[I 2021-05-16 16:46:40.973 LabApp] JupyterLab application directory is /srv/conda/envs/notebook/share/jupyter/lab
[I 16:46:40.982 NotebookApp] nteract extension loaded from /srv/conda/envs/notebook/lib/python3.7/site-packages/nteract_on_jupyter
[I 16:46:40.985 NotebookApp] Will shut down after 600 seconds with no kernels or terminals.
[I 16:46:40.986 NotebookApp] Serving notebooks from local directory: /home/jovyan
[I 16:46:40.986 NotebookApp] Jupyter Notebook 6.2.0 is running at:
[I 16:46:40.986 NotebookApp] http://jupyter-ra5hid-2dpm-2dnbinteract-2dtutorial-2da8klkqv9:8888/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/?token=...
[I 16:46:40.986 NotebookApp]  or http://127.0.0.1:8888/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/?token=...
[I 16:46:40.986 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 16:46:40.992 NotebookApp] No web browser found: could not locate runnable browser.
[I 16:46:41.314 NotebookApp] 302 GET /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/ (10.0.5.13) 1.300000ms
[I 16:46:49.534 NotebookApp] 302 GET /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/?token=g6wSLpElSvm6SEGKAR_LIw (117.196.252.225) 1.110000ms
[I 16:48:02.048 NotebookApp] Creating new notebook in 
[I 16:48:02.067 NotebookApp] Writing notebook-signing key to /home/jovyan/.local/share/jupyter/notebook_secret
[W 16:48:12.285 NotebookApp] Notebook Matplotlib Exercises .ipynb is not trusted
[I 16:48:14.759 NotebookApp] Kernel started: 03223824-f060-4d0f-a998-f3eea0a10b06, name: python3
[I 16:48:14.759 NotebookApp] Culling kernels with idle durations > 600 seconds at 60 second intervals ...
[I 16:48:14.760 NotebookApp] Culling kernels even with connected clients
[I 16:48:15.050 NotebookApp] Kernel started: b0e29746-92be-40fc-b524-08dae7a5ed02, name: python3
[I 16:50:14.999 NotebookApp] Saving file at /Curries.ipynb
[E 16:50:15.007 NotebookApp] Error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
    Traceback (most recent call last):
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 477, in save
        self._save_notebook(os_path, nb)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 291, in _save_notebook
        nbformat.write(nb, f, version=nbformat.NO_CONVERT)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/__init__.py", line 164, in write
        return write(nb, f, version=version, **kwargs)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/__init__.py", line 107, in writes
        try:
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/validator.py", line 266, in validate
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/words.py", line 20, in generate_corpus_id
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/words.py", line 15, in acceptable_adjectives
    FileNotFoundError: [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[W 16:50:15.010 NotebookApp] 500 PUT /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/contents/Curries.ipynb (117.196.252.225): Unexpected error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[W 16:50:15.011 NotebookApp] Unexpected error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[E 16:50:15.012 NotebookApp] {
      "Cookie": "username-hub-gke2-mybinder-org=\"2|1:0|10:1621183609|30:username-hub-gke2-mybinder-org|44:YWJjYjcwMmU4MGExNDVmMzk3OGI3ZjBlNmNhZThmNjM=|4e45eb32acba1f080bba177582f5c38822597a4ab96a64e906cca8c3b87a0607\"; _xsrf=2|34e9a513|5bd98113160380829d02d69d0fba51f4|1621183609",
      "Referer": "https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/Curries.ipynb",
      "Origin": "https://hub.gke2.mybinder.org",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|34e9a513|5bd98113160380829d02d69d0fba51f4|1621183609",
      "Content-Type": "application/json",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.5",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0",
      "Content-Length": "18220",
      "X-Scheme": "https",
      "X-Forwarded-Port": "443,80",
      "X-Forwarded-Host": "hub.gke2.mybinder.org",
      "X-Forwarded-Proto": "https,http",
      "X-Forwarded-For": "117.196.252.225,::ffff:10.0.14.6",
      "X-Real-Ip": "117.196.252.225",
      "X-Request-Id": "8ad3d92aa15af9a589038a91cece9232",
      "Host": "hub.gke2.mybinder.org",
      "Connection": "close"
    }
[E 16:50:15.013 NotebookApp] 500 PUT /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/contents/Curries.ipynb (117.196.252.225) 13.590000ms referer=https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/Curries.ipynb
[I 16:50:16.610 NotebookApp] Saving file at /Matplotlib Exercises .ipynb
[W 16:50:16.611 NotebookApp] Notebook Matplotlib Exercises .ipynb is not trusted
[I 16:50:28.978 NotebookApp] Saving file at /Curries.ipynb
[E 16:50:28.991 NotebookApp] Error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
    Traceback (most recent call last):
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 477, in save
        self._save_notebook(os_path, nb)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 291, in _save_notebook
        nbformat.write(nb, f, version=nbformat.NO_CONVERT)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/__init__.py", line 164, in write
        return write(nb, f, version=version, **kwargs)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/__init__.py", line 107, in writes
        try:
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/validator.py", line 266, in validate
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/words.py", line 20, in generate_corpus_id
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/words.py", line 15, in acceptable_adjectives
    FileNotFoundError: [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[W 16:50:28.991 NotebookApp] 500 PUT /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/contents/Curries.ipynb (117.196.252.225): Unexpected error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[W 16:50:28.992 NotebookApp] Unexpected error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[E 16:50:28.993 NotebookApp] {
      "Cookie": "username-hub-gke2-mybinder-org=\"2|1:0|10:1621183609|30:username-hub-gke2-mybinder-org|44:YWJjYjcwMmU4MGExNDVmMzk3OGI3ZjBlNmNhZThmNjM=|4e45eb32acba1f080bba177582f5c38822597a4ab96a64e906cca8c3b87a0607\"; _xsrf=2|34e9a513|5bd98113160380829d02d69d0fba51f4|1621183609",
      "Referer": "https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/Curries.ipynb",
      "Origin": "https://hub.gke2.mybinder.org",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|34e9a513|5bd98113160380829d02d69d0fba51f4|1621183609",
      "Content-Type": "application/json",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.5",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0",
      "Content-Length": "18220",
      "X-Scheme": "https",
      "X-Forwarded-Port": "443,80",
      "X-Forwarded-Host": "hub.gke2.mybinder.org",
      "X-Forwarded-Proto": "https,http",
      "X-Forwarded-For": "117.196.252.225,::ffff:10.0.14.6",
      "X-Real-Ip": "117.196.252.225",
      "X-Request-Id": "644e1b92d18de795265264386988d463",
      "Host": "hub.gke2.mybinder.org",
      "Connection": "close"
    }
[E 16:50:28.993 NotebookApp] 500 PUT /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/contents/Curries.ipynb (117.196.252.225) 15.890000ms referer=https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/Curries.ipynb
[I 16:50:33.829 NotebookApp] Starting buffering for 03223824-f060-4d0f-a998-f3eea0a10b06:d60f50bf7a1645529625a7f2925449d8
[I 16:52:35.626 NotebookApp] Saving file at /Curries.ipynb
[E 16:52:35.633 NotebookApp] Error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
    Traceback (most recent call last):
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 477, in save
        self._save_notebook(os_path, nb)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 291, in _save_notebook
        nbformat.write(nb, f, version=nbformat.NO_CONVERT)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/__init__.py", line 164, in write
        return write(nb, f, version=version, **kwargs)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/__init__.py", line 107, in writes
        try:
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/validator.py", line 266, in validate
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/words.py", line 20, in generate_corpus_id
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/words.py", line 15, in acceptable_adjectives
    FileNotFoundError: [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[W 16:52:35.633 NotebookApp] 500 PUT /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/contents/Curries.ipynb (117.196.252.225): Unexpected error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[W 16:52:35.634 NotebookApp] Unexpected error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[E 16:52:35.634 NotebookApp] {
      "Cookie": "username-hub-gke2-mybinder-org=\"2|1:0|10:1621183609|30:username-hub-gke2-mybinder-org|44:YWJjYjcwMmU4MGExNDVmMzk3OGI3ZjBlNmNhZThmNjM=|4e45eb32acba1f080bba177582f5c38822597a4ab96a64e906cca8c3b87a0607\"; _xsrf=2|34e9a513|5bd98113160380829d02d69d0fba51f4|1621183609",
      "Referer": "https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/Curries.ipynb",
      "Origin": "https://hub.gke2.mybinder.org",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|34e9a513|5bd98113160380829d02d69d0fba51f4|1621183609",
      "Content-Type": "application/json",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.5",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0",
      "Content-Length": "1006",
      "X-Scheme": "https",
      "X-Forwarded-Port": "443,80",
      "X-Forwarded-Host": "hub.gke2.mybinder.org",
      "X-Forwarded-Proto": "https,http",
      "X-Forwarded-For": "117.196.252.225,::ffff:10.0.14.6",
      "X-Real-Ip": "117.196.252.225",
      "X-Request-Id": "e375f9a497557086ba3c608924d49c79",
      "Host": "hub.gke2.mybinder.org",
      "Connection": "close"
    }
[E 16:52:35.634 NotebookApp] 500 PUT /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/contents/Curries.ipynb (117.196.252.225) 9.820000ms referer=https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/Curries.ipynb
[I 16:54:35.651 NotebookApp] Saving file at /Curries.ipynb
[E 16:54:35.657 NotebookApp] Error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
    Traceback (most recent call last):
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 477, in save
        self._save_notebook(os_path, nb)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 291, in _save_notebook
        nbformat.write(nb, f, version=nbformat.NO_CONVERT)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/__init__.py", line 164, in write
        return write(nb, f, version=version, **kwargs)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/__init__.py", line 107, in writes
        try:
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/validator.py", line 266, in validate
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/words.py", line 20, in generate_corpus_id
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/words.py", line 15, in acceptable_adjectives
    FileNotFoundError: [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[W 16:54:35.658 NotebookApp] 500 PUT /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/contents/Curries.ipynb (117.196.252.225): Unexpected error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[W 16:54:35.658 NotebookApp] Unexpected error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[E 16:54:35.659 NotebookApp] {
      "Cookie": "username-hub-gke2-mybinder-org=\"2|1:0|10:1621183609|30:username-hub-gke2-mybinder-org|44:YWJjYjcwMmU4MGExNDVmMzk3OGI3ZjBlNmNhZThmNjM=|4e45eb32acba1f080bba177582f5c38822597a4ab96a64e906cca8c3b87a0607\"; _xsrf=2|34e9a513|5bd98113160380829d02d69d0fba51f4|1621183609",
      "Referer": "https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/Curries.ipynb",
      "Origin": "https://hub.gke2.mybinder.org",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|34e9a513|5bd98113160380829d02d69d0fba51f4|1621183609",
      "Content-Type": "application/json",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.5",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0",
      "Content-Length": "694",
      "X-Scheme": "https",
      "X-Forwarded-Port": "443,80",
      "X-Forwarded-Host": "hub.gke2.mybinder.org",
      "X-Forwarded-Proto": "https,http",
      "X-Forwarded-For": "117.196.252.225,::ffff:10.0.14.6",
      "X-Real-Ip": "117.196.252.225",
      "X-Request-Id": "c20c0ad7cb41354e71f693b75cc17a4a",
      "Host": "hub.gke2.mybinder.org",
      "Connection": "close"
    }
[E 16:54:35.659 NotebookApp] 500 PUT /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/contents/Curries.ipynb (117.196.252.225) 8.770000ms referer=https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/Curries.ipynb
[I 16:56:35.628 NotebookApp] Saving file at /Curries.ipynb
[E 16:56:35.637 NotebookApp] Error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
    Traceback (most recent call last):
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 477, in save
        self._save_notebook(os_path, nb)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 291, in _save_notebook
        nbformat.write(nb, f, version=nbformat.NO_CONVERT)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/__init__.py", line 164, in write
        return write(nb, f, version=version, **kwargs)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/__init__.py", line 107, in writes
        try:
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/validator.py", line 266, in validate
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/words.py", line 20, in generate_corpus_id
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/words.py", line 15, in acceptable_adjectives
    FileNotFoundError: [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[W 16:56:35.638 NotebookApp] 500 PUT /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/contents/Curries.ipynb (117.196.252.225): Unexpected error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[W 16:56:35.638 NotebookApp] Unexpected error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[E 16:56:35.640 NotebookApp] {
      "Cookie": "username-hub-gke2-mybinder-org=\"2|1:0|10:1621183609|30:username-hub-gke2-mybinder-org|44:YWJjYjcwMmU4MGExNDVmMzk3OGI3ZjBlNmNhZThmNjM=|4e45eb32acba1f080bba177582f5c38822597a4ab96a64e906cca8c3b87a0607\"; _xsrf=2|34e9a513|5bd98113160380829d02d69d0fba51f4|1621183609",
      "Referer": "https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/Curries.ipynb",
      "Origin": "https://hub.gke2.mybinder.org",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|34e9a513|5bd98113160380829d02d69d0fba51f4|1621183609",
      "Content-Type": "application/json",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.5",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0",
      "Content-Length": "1080",
      "X-Scheme": "https",
      "X-Forwarded-Port": "443,80",
      "X-Forwarded-Host": "hub.gke2.mybinder.org",
      "X-Forwarded-Proto": "https,http",
      "X-Forwarded-For": "117.196.252.225,::ffff:10.0.14.6",
      "X-Real-Ip": "117.196.252.225",
      "X-Request-Id": "4d7707e8a1b8e24dba2fab08dda6673d",
      "Host": "hub.gke2.mybinder.org",
      "Connection": "close"
    }
[E 16:56:35.640 NotebookApp] 500 PUT /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/contents/Curries.ipynb (117.196.252.225) 12.450000ms referer=https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/Curries.ipynb
[I 16:58:35.645 NotebookApp] Saving file at /Curries.ipynb
[E 16:58:35.657 NotebookApp] Error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
    Traceback (most recent call last):
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 477, in save
        self._save_notebook(os_path, nb)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 291, in _save_notebook
        nbformat.write(nb, f, version=nbformat.NO_CONVERT)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/__init__.py", line 164, in write
        return write(nb, f, version=version, **kwargs)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/__init__.py", line 107, in writes
        try:
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/validator.py", line 266, in validate
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/words.py", line 20, in generate_corpus_id
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/words.py", line 15, in acceptable_adjectives
    FileNotFoundError: [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[W 16:58:35.658 NotebookApp] 500 PUT /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/contents/Curries.ipynb (117.196.252.225): Unexpected error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[W 16:58:35.658 NotebookApp] Unexpected error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[E 16:58:35.659 NotebookApp] {
      "Cookie": "username-hub-gke2-mybinder-org=\"2|1:0|10:1621183609|30:username-hub-gke2-mybinder-org|44:YWJjYjcwMmU4MGExNDVmMzk3OGI3ZjBlNmNhZThmNjM=|4e45eb32acba1f080bba177582f5c38822597a4ab96a64e906cca8c3b87a0607\"; _xsrf=2|34e9a513|5bd98113160380829d02d69d0fba51f4|1621183609",
      "Referer": "https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/Curries.ipynb",
      "Origin": "https://hub.gke2.mybinder.org",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|34e9a513|5bd98113160380829d02d69d0fba51f4|1621183609",
      "Content-Type": "application/json",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.5",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0",
      "Content-Length": "1080",
      "X-Scheme": "https",
      "X-Forwarded-Port": "443,80",
      "X-Forwarded-Host": "hub.gke2.mybinder.org",
      "X-Forwarded-Proto": "https,http",
      "X-Forwarded-For": "117.196.252.225,::ffff:10.0.14.6",
      "X-Real-Ip": "117.196.252.225",
      "X-Request-Id": "f950d60b0ae637d7c8dc76a017555841",
      "Host": "hub.gke2.mybinder.org",
      "Connection": "close"
    }
[E 16:58:35.659 NotebookApp] 500 PUT /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/contents/Curries.ipynb (117.196.252.225) 15.120000ms referer=https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/Curries.ipynb
[W 16:59:14.761 NotebookApp] Culling 'idle' kernel 'python3' (b0e29746-92be-40fc-b524-08dae7a5ed02) with 1 connections due to 655 seconds of inactivity.
[I 16:59:14.762 NotebookApp] Kernel shutdown: b0e29746-92be-40fc-b524-08dae7a5ed02
[W 16:59:15.421 NotebookApp] 410 DELETE /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/sessions/2db19990-1d32-4a1b-a80d-bed16fa04f56 (117.196.252.225): Kernel deleted before session
[W 16:59:15.421 NotebookApp] Kernel deleted before session
[W 16:59:15.421 NotebookApp] 410 DELETE /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/sessions/2db19990-1d32-4a1b-a80d-bed16fa04f56 (117.196.252.225) 1.790000ms referer=https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/Matplotlib%20Exercises%20.ipynb
[I 16:59:16.078 NotebookApp] Starting buffering for 03223824-f060-4d0f-a998-f3eea0a10b06:39512f4b9abd46e1a5e066704efdc59d
[W 16:59:33.325 NotebookApp] 404 DELETE /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/sessions/2db19990-1d32-4a1b-a80d-bed16fa04f56 (117.196.252.225): Session not found: session_id='2db19990-1d32-4a1b-a80d-bed16fa04f56'
[W 16:59:33.326 NotebookApp] Session not found: session_id='2db19990-1d32-4a1b-a80d-bed16fa04f56'
[W 16:59:33.326 NotebookApp] 404 DELETE /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/sessions/2db19990-1d32-4a1b-a80d-bed16fa04f56 (117.196.252.225) 2.000000ms referer=https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/Matplotlib%20Exercises%20.ipynb
[I 16:59:33.620 NotebookApp] Kernel started: 62eb9fe2-8233-421e-a807-efc776629f60, name: python3
[I 17:01:18.298 NotebookApp] Saving file at /Curries.ipynb
[E 17:01:18.306 NotebookApp] Error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
    Traceback (most recent call last):
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 477, in save
        self._save_notebook(os_path, nb)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 291, in _save_notebook
        nbformat.write(nb, f, version=nbformat.NO_CONVERT)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/__init__.py", line 164, in write
        return write(nb, f, version=version, **kwargs)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/__init__.py", line 107, in writes
        try:
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/validator.py", line 266, in validate
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/words.py", line 20, in generate_corpus_id
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/words.py", line 15, in acceptable_adjectives
    FileNotFoundError: [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[W 17:01:18.307 NotebookApp] 500 PUT /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/contents/Curries.ipynb (117.196.252.225): Unexpected error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[W 17:01:18.307 NotebookApp] Unexpected error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[E 17:01:18.308 NotebookApp] {
      "Cookie": "username-hub-gke2-mybinder-org=\"2|1:0|10:1621183609|30:username-hub-gke2-mybinder-org|44:YWJjYjcwMmU4MGExNDVmMzk3OGI3ZjBlNmNhZThmNjM=|4e45eb32acba1f080bba177582f5c38822597a4ab96a64e906cca8c3b87a0607\"; _xsrf=2|34e9a513|5bd98113160380829d02d69d0fba51f4|1621183609",
      "Referer": "https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/Curries.ipynb",
      "Origin": "https://hub.gke2.mybinder.org",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|34e9a513|5bd98113160380829d02d69d0fba51f4|1621183609",
      "Content-Type": "application/json",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.5",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0",
      "Content-Length": "622",
      "X-Scheme": "https",
      "X-Forwarded-Port": "443,80",
      "X-Forwarded-Host": "hub.gke2.mybinder.org",
      "X-Forwarded-Proto": "https,http",
      "X-Forwarded-For": "117.196.252.225,::ffff:10.0.14.6",
      "X-Real-Ip": "117.196.252.225",
      "X-Request-Id": "85a21d05fa90486c66257e99ed1463bd",
      "Host": "hub.gke2.mybinder.org",
      "Connection": "close"
    }
[E 17:01:18.308 NotebookApp] 500 PUT /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/contents/Curries.ipynb (117.196.252.225) 10.870000ms referer=https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/Curries.ipynb
[I 17:01:25.650 NotebookApp] Saving file at /Curries.ipynb
[E 17:01:25.664 NotebookApp] Error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
    Traceback (most recent call last):
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 477, in save
        self._save_notebook(os_path, nb)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 291, in _save_notebook
        nbformat.write(nb, f, version=nbformat.NO_CONVERT)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/__init__.py", line 164, in write
        return write(nb, f, version=version, **kwargs)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/__init__.py", line 107, in writes
        try:
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/validator.py", line 266, in validate
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/words.py", line 20, in generate_corpus_id
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/words.py", line 15, in acceptable_adjectives
    FileNotFoundError: [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[W 17:01:25.665 NotebookApp] 500 PUT /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/contents/Curries.ipynb (117.196.252.225): Unexpected error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[W 17:01:25.665 NotebookApp] Unexpected error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[E 17:01:25.666 NotebookApp] {
      "Cookie": "username-hub-gke2-mybinder-org=\"2|1:0|10:1621183609|30:username-hub-gke2-mybinder-org|44:YWJjYjcwMmU4MGExNDVmMzk3OGI3ZjBlNmNhZThmNjM=|4e45eb32acba1f080bba177582f5c38822597a4ab96a64e906cca8c3b87a0607\"; _xsrf=2|34e9a513|5bd98113160380829d02d69d0fba51f4|1621183609",
      "Referer": "https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/Curries.ipynb",
      "Origin": "https://hub.gke2.mybinder.org",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|34e9a513|5bd98113160380829d02d69d0fba51f4|1621183609",
      "Content-Type": "application/json",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.5",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0",
      "Content-Length": "622",
      "X-Scheme": "https",
      "X-Forwarded-Port": "443,80",
      "X-Forwarded-Host": "hub.gke2.mybinder.org",
      "X-Forwarded-Proto": "https,http",
      "X-Forwarded-For": "117.196.252.225,::ffff:10.0.14.6",
      "X-Real-Ip": "117.196.252.225",
      "X-Request-Id": "baf8e2f13b5d6e953b9ccf3353009c90",
      "Host": "hub.gke2.mybinder.org",
      "Connection": "close"
    }
[E 17:01:25.666 NotebookApp] 500 PUT /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/contents/Curries.ipynb (117.196.252.225) 16.630000ms referer=https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/Curries.ipynb
[I 17:01:30.214 NotebookApp] Starting buffering for 03223824-f060-4d0f-a998-f3eea0a10b06:80375857c30f44f08fe3b026f6e0daf9
[I 17:01:34.632 NotebookApp] Saving file at /Curries.ipynb
[E 17:01:34.644 NotebookApp] Error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
    Traceback (most recent call last):
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 477, in save
        self._save_notebook(os_path, nb)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 291, in _save_notebook
        nbformat.write(nb, f, version=nbformat.NO_CONVERT)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/__init__.py", line 164, in write
        return write(nb, f, version=version, **kwargs)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/__init__.py", line 107, in writes
        try:
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/validator.py", line 266, in validate
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/words.py", line 20, in generate_corpus_id
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/words.py", line 15, in acceptable_adjectives
    FileNotFoundError: [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[W 17:01:34.644 NotebookApp] 500 PUT /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/contents/Curries.ipynb (117.196.252.225): Unexpected error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[W 17:01:34.645 NotebookApp] Unexpected error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[E 17:01:34.646 NotebookApp] {
      "Cookie": "username-hub-gke2-mybinder-org=\"2|1:0|10:1621183609|30:username-hub-gke2-mybinder-org|44:YWJjYjcwMmU4MGExNDVmMzk3OGI3ZjBlNmNhZThmNjM=|4e45eb32acba1f080bba177582f5c38822597a4ab96a64e906cca8c3b87a0607\"; _xsrf=2|34e9a513|5bd98113160380829d02d69d0fba51f4|1621183609",
      "Referer": "https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/Curries.ipynb",
      "Origin": "https://hub.gke2.mybinder.org",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|34e9a513|5bd98113160380829d02d69d0fba51f4|1621183609",
      "Content-Type": "application/json",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.5",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0",
      "Content-Length": "471",
      "X-Scheme": "https",
      "X-Forwarded-Port": "443,80",
      "X-Forwarded-Host": "hub.gke2.mybinder.org",
      "X-Forwarded-Proto": "https,http",
      "X-Forwarded-For": "117.196.252.225,::ffff:10.0.14.6",
      "X-Real-Ip": "117.196.252.225",
      "X-Request-Id": "8cf6809736bb4c8343a76ba84dee629f",
      "Host": "hub.gke2.mybinder.org",
      "Connection": "close"
    }
[E 17:01:34.646 NotebookApp] 500 PUT /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/contents/Curries.ipynb (117.196.252.225) 14.980000ms referer=https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/Curries.ipynb
[I 17:03:31.905 NotebookApp] Saving file at /Curries.ipynb
[E 17:03:32.390 NotebookApp] Error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
    Traceback (most recent call last):
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 477, in save
        self._save_notebook(os_path, nb)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 291, in _save_notebook
        nbformat.write(nb, f, version=nbformat.NO_CONVERT)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/__init__.py", line 164, in write
        return write(nb, f, version=version, **kwargs)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/__init__.py", line 107, in writes
        try:
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/validator.py", line 266, in validate
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/words.py", line 20, in generate_corpus_id
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/words.py", line 15, in acceptable_adjectives
    FileNotFoundError: [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[W 17:03:32.391 NotebookApp] 500 PUT /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/contents/Curries.ipynb (117.196.252.225): Unexpected error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[W 17:03:32.391 NotebookApp] Unexpected error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[E 17:03:32.392 NotebookApp] {
      "Cookie": "username-hub-gke2-mybinder-org=\"2|1:0|10:1621183609|30:username-hub-gke2-mybinder-org|44:YWJjYjcwMmU4MGExNDVmMzk3OGI3ZjBlNmNhZThmNjM=|4e45eb32acba1f080bba177582f5c38822597a4ab96a64e906cca8c3b87a0607\"; _xsrf=2|34e9a513|5bd98113160380829d02d69d0fba51f4|1621183609",
      "Referer": "https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/Curries.ipynb",
      "Origin": "https://hub.gke2.mybinder.org",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|34e9a513|5bd98113160380829d02d69d0fba51f4|1621183609",
      "Content-Type": "application/json",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.5",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0",
      "Content-Length": "471",
      "X-Scheme": "https",
      "X-Forwarded-Port": "443,80",
      "X-Forwarded-Host": "hub.gke2.mybinder.org",
      "X-Forwarded-Proto": "https,http",
      "X-Forwarded-For": "117.196.252.225,::ffff:10.0.14.6",
      "X-Real-Ip": "117.196.252.225",
      "X-Request-Id": "f2610ee520ddef81d36a8c1b5a2ab5f2",
      "Host": "hub.gke2.mybinder.org",
      "Connection": "close"
    }
[E 17:03:32.392 NotebookApp] 500 PUT /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/contents/Curries.ipynb (117.196.252.225) 488.530000ms referer=https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/Curries.ipynb
[I 17:04:43.469 NotebookApp] New terminal with automatic name: 1
TermSocket.open: 1
TermSocket.open: Opened 1
[I 17:05:31.959 NotebookApp] Saving file at /Curries.ipynb
[E 17:05:32.122 NotebookApp] Error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
    Traceback (most recent call last):
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 477, in save
        self._save_notebook(os_path, nb)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 291, in _save_notebook
        nbformat.write(nb, f, version=nbformat.NO_CONVERT)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/__init__.py", line 164, in write
        return write(nb, f, version=version, **kwargs)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/__init__.py", line 107, in writes
        try:
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/validator.py", line 266, in validate
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/words.py", line 20, in generate_corpus_id
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/words.py", line 15, in acceptable_adjectives
    FileNotFoundError: [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[W 17:05:32.123 NotebookApp] 500 PUT /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/contents/Curries.ipynb (117.196.252.225): Unexpected error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[W 17:05:32.123 NotebookApp] Unexpected error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[E 17:05:32.124 NotebookApp] {
      "Cookie": "username-hub-gke2-mybinder-org=\"2|1:0|10:1621183609|30:username-hub-gke2-mybinder-org|44:YWJjYjcwMmU4MGExNDVmMzk3OGI3ZjBlNmNhZThmNjM=|4e45eb32acba1f080bba177582f5c38822597a4ab96a64e906cca8c3b87a0607\"; _xsrf=2|34e9a513|5bd98113160380829d02d69d0fba51f4|1621183609",
      "Referer": "https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/Curries.ipynb",
      "Origin": "https://hub.gke2.mybinder.org",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|34e9a513|5bd98113160380829d02d69d0fba51f4|1621183609",
      "Content-Type": "application/json",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.5",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0",
      "Content-Length": "471",
      "X-Scheme": "https",
      "X-Forwarded-Port": "443,80",
      "X-Forwarded-Host": "hub.gke2.mybinder.org",
      "X-Forwarded-Proto": "https,http",
      "X-Forwarded-For": "117.196.252.225,::ffff:10.0.14.6",
      "X-Real-Ip": "117.196.252.225",
      "X-Request-Id": "5d75646d807de35e71c8c1daadea5928",
      "Host": "hub.gke2.mybinder.org",
      "Connection": "close"
    }
[E 17:05:32.124 NotebookApp] 500 PUT /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/contents/Curries.ipynb (117.196.252.225) 166.640000ms referer=https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/Curries.ipynb
[I 17:07:31.933 NotebookApp] Saving file at /Curries.ipynb
[E 17:07:31.948 NotebookApp] Error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
    Traceback (most recent call last):
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 477, in save
        self._save_notebook(os_path, nb)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 291, in _save_notebook
        nbformat.write(nb, f, version=nbformat.NO_CONVERT)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/__init__.py", line 164, in write
        return write(nb, f, version=version, **kwargs)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/__init__.py", line 107, in writes
        try:
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/validator.py", line 266, in validate
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/words.py", line 20, in generate_corpus_id
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/words.py", line 15, in acceptable_adjectives
    FileNotFoundError: [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[W 17:07:31.948 NotebookApp] 500 PUT /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/contents/Curries.ipynb (117.196.252.225): Unexpected error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[W 17:07:31.949 NotebookApp] Unexpected error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[E 17:07:31.949 NotebookApp] {
      "Cookie": "username-hub-gke2-mybinder-org=\"2|1:0|10:1621183609|30:username-hub-gke2-mybinder-org|44:YWJjYjcwMmU4MGExNDVmMzk3OGI3ZjBlNmNhZThmNjM=|4e45eb32acba1f080bba177582f5c38822597a4ab96a64e906cca8c3b87a0607\"; _xsrf=2|34e9a513|5bd98113160380829d02d69d0fba51f4|1621183609",
      "Referer": "https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/Curries.ipynb",
      "Origin": "https://hub.gke2.mybinder.org",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|34e9a513|5bd98113160380829d02d69d0fba51f4|1621183609",
      "Content-Type": "application/json",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.5",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0",
      "Content-Length": "471",
      "X-Scheme": "https",
      "X-Forwarded-Port": "443,80",
      "X-Forwarded-Host": "hub.gke2.mybinder.org",
      "X-Forwarded-Proto": "https,http",
      "X-Forwarded-For": "117.196.252.225,::ffff:10.0.14.6",
      "X-Real-Ip": "117.196.252.225",
      "X-Request-Id": "c952b164da69547ed674a81bec19512d",
      "Host": "hub.gke2.mybinder.org",
      "Connection": "close"
    }
[E 17:07:31.949 NotebookApp] 500 PUT /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/contents/Curries.ipynb (117.196.252.225) 17.070000ms referer=https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/Curries.ipynb
[I 17:09:31.927 NotebookApp] Saving file at /Curries.ipynb
[E 17:09:31.943 NotebookApp] Error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
    Traceback (most recent call last):
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 477, in save
        self._save_notebook(os_path, nb)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 291, in _save_notebook
        nbformat.write(nb, f, version=nbformat.NO_CONVERT)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/__init__.py", line 164, in write
        return write(nb, f, version=version, **kwargs)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/__init__.py", line 107, in writes
        try:
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/validator.py", line 266, in validate
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/words.py", line 20, in generate_corpus_id
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/words.py", line 15, in acceptable_adjectives
    FileNotFoundError: [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[W 17:09:31.944 NotebookApp] 500 PUT /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/contents/Curries.ipynb (117.196.252.225): Unexpected error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[W 17:09:31.944 NotebookApp] Unexpected error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[E 17:09:31.945 NotebookApp] {
      "Cookie": "username-hub-gke2-mybinder-org=\"2|1:0|10:1621183609|30:username-hub-gke2-mybinder-org|44:YWJjYjcwMmU4MGExNDVmMzk3OGI3ZjBlNmNhZThmNjM=|4e45eb32acba1f080bba177582f5c38822597a4ab96a64e906cca8c3b87a0607\"; _xsrf=2|34e9a513|5bd98113160380829d02d69d0fba51f4|1621183609",
      "Referer": "https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/Curries.ipynb",
      "Origin": "https://hub.gke2.mybinder.org",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|34e9a513|5bd98113160380829d02d69d0fba51f4|1621183609",
      "Content-Type": "application/json",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.5",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0",
      "Content-Length": "471",
      "X-Scheme": "https",
      "X-Forwarded-Port": "443,80",
      "X-Forwarded-Host": "hub.gke2.mybinder.org",
      "X-Forwarded-Proto": "https,http",
      "X-Forwarded-For": "117.196.252.225,::ffff:10.0.14.6",
      "X-Real-Ip": "117.196.252.225",
      "X-Request-Id": "0b378c5f2d3f73108d434a2f236e1801",
      "Host": "hub.gke2.mybinder.org",
      "Connection": "close"
    }
[E 17:09:31.945 NotebookApp] 500 PUT /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/contents/Curries.ipynb (117.196.252.225) 18.560000ms referer=https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/Curries.ipynb
[W 17:10:14.762 NotebookApp] Culling 'idle' kernel 'python3' (62eb9fe2-8233-421e-a807-efc776629f60) with 1 connections due to 640 seconds of inactivity.
[I 17:10:14.763 NotebookApp] Kernel shutdown: 62eb9fe2-8233-421e-a807-efc776629f60
[W 17:10:15.364 NotebookApp] 410 DELETE /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/sessions/fc7e23ad-6eb0-43a8-a8f3-f7929789a75b (117.196.252.225): Kernel deleted before session
[W 17:10:15.364 NotebookApp] Kernel deleted before session
[W 17:10:15.365 NotebookApp] 410 DELETE /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/sessions/fc7e23ad-6eb0-43a8-a8f3-f7929789a75b (117.196.252.225) 2.010000ms referer=https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/Matplotlib%20Exercises%20.ipynb
[I 17:11:31.927 NotebookApp] Saving file at /Curries.ipynb
[E 17:11:31.991 NotebookApp] Error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
    Traceback (most recent call last):
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 477, in save
        self._save_notebook(os_path, nb)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 291, in _save_notebook
        nbformat.write(nb, f, version=nbformat.NO_CONVERT)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/__init__.py", line 164, in write
        return write(nb, f, version=version, **kwargs)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/__init__.py", line 107, in writes
        try:
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/validator.py", line 266, in validate
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/words.py", line 20, in generate_corpus_id
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/words.py", line 15, in acceptable_adjectives
    FileNotFoundError: [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[W 17:11:31.992 NotebookApp] 500 PUT /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/contents/Curries.ipynb (117.196.252.225): Unexpected error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[W 17:11:31.992 NotebookApp] Unexpected error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[E 17:11:31.993 NotebookApp] {
      "Cookie": "username-hub-gke2-mybinder-org=\"2|1:0|10:1621183609|30:username-hub-gke2-mybinder-org|44:YWJjYjcwMmU4MGExNDVmMzk3OGI3ZjBlNmNhZThmNjM=|4e45eb32acba1f080bba177582f5c38822597a4ab96a64e906cca8c3b87a0607\"; _xsrf=2|34e9a513|5bd98113160380829d02d69d0fba51f4|1621183609",
      "Referer": "https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/Curries.ipynb",
      "Origin": "https://hub.gke2.mybinder.org",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|34e9a513|5bd98113160380829d02d69d0fba51f4|1621183609",
      "Content-Type": "application/json",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.5",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0",
      "Content-Length": "471",
      "X-Scheme": "https",
      "X-Forwarded-Port": "443,80",
      "X-Forwarded-Host": "hub.gke2.mybinder.org",
      "X-Forwarded-Proto": "https,http",
      "X-Forwarded-For": "117.196.252.225,::ffff:10.0.14.6",
      "X-Real-Ip": "117.196.252.225",
      "X-Request-Id": "d5335c4a611117a014af36d73fca54b7",
      "Host": "hub.gke2.mybinder.org",
      "Connection": "close"
    }
[E 17:11:31.993 NotebookApp] 500 PUT /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/contents/Curries.ipynb (117.196.252.225) 67.420000ms referer=https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/Curries.ipynb
[W 17:12:14.762 NotebookApp] Culling 'idle' kernel 'python3' (03223824-f060-4d0f-a998-f3eea0a10b06) with 1 connections due to 641 seconds of inactivity.
[I 17:12:14.763 NotebookApp] Kernel shutdown: 03223824-f060-4d0f-a998-f3eea0a10b06
[W 17:12:15.346 NotebookApp] 410 DELETE /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/sessions/f7abf295-16b7-47a9-8a4e-870587c174c9 (117.196.252.225): Kernel deleted before session
[W 17:12:15.346 NotebookApp] Kernel deleted before session
[W 17:12:15.347 NotebookApp] 410 DELETE /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/sessions/f7abf295-16b7-47a9-8a4e-870587c174c9 (117.196.252.225) 1.870000ms referer=https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/Curries.ipynb
[I 17:13:31.932 NotebookApp] Saving file at /Curries.ipynb
[E 17:13:31.947 NotebookApp] Error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
    Traceback (most recent call last):
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 477, in save
        self._save_notebook(os_path, nb)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 291, in _save_notebook
        nbformat.write(nb, f, version=nbformat.NO_CONVERT)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/__init__.py", line 164, in write
        return write(nb, f, version=version, **kwargs)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/__init__.py", line 107, in writes
        try:
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/validator.py", line 266, in validate
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/words.py", line 20, in generate_corpus_id
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/words.py", line 15, in acceptable_adjectives
    FileNotFoundError: [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[W 17:13:31.948 NotebookApp] 500 PUT /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/contents/Curries.ipynb (117.196.252.225): Unexpected error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[W 17:13:31.948 NotebookApp] Unexpected error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[E 17:13:31.949 NotebookApp] {
      "Cookie": "username-hub-gke2-mybinder-org=\"2|1:0|10:1621183609|30:username-hub-gke2-mybinder-org|44:YWJjYjcwMmU4MGExNDVmMzk3OGI3ZjBlNmNhZThmNjM=|4e45eb32acba1f080bba177582f5c38822597a4ab96a64e906cca8c3b87a0607\"; _xsrf=2|34e9a513|5bd98113160380829d02d69d0fba51f4|1621183609",
      "Referer": "https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/Curries.ipynb",
      "Origin": "https://hub.gke2.mybinder.org",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|34e9a513|5bd98113160380829d02d69d0fba51f4|1621183609",
      "Content-Type": "application/json",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.5",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0",
      "Content-Length": "471",
      "X-Scheme": "https",
      "X-Forwarded-Port": "443,80",
      "X-Forwarded-Host": "hub.gke2.mybinder.org",
      "X-Forwarded-Proto": "https,http",
      "X-Forwarded-For": "117.196.252.225,::ffff:10.0.14.6",
      "X-Real-Ip": "117.196.252.225",
      "X-Request-Id": "f891c0a994ca4761b7f445becf04ca10",
      "Host": "hub.gke2.mybinder.org",
      "Connection": "close"
    }
[E 17:13:31.949 NotebookApp] 500 PUT /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/contents/Curries.ipynb (117.196.252.225) 17.000000ms referer=https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/Curries.ipynb
[I 17:15:31.945 NotebookApp] Saving file at /Curries.ipynb
[E 17:15:31.968 NotebookApp] Error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
    Traceback (most recent call last):
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 477, in save
        self._save_notebook(os_path, nb)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 291, in _save_notebook
        nbformat.write(nb, f, version=nbformat.NO_CONVERT)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/__init__.py", line 164, in write
        return write(nb, f, version=version, **kwargs)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/__init__.py", line 107, in writes
        try:
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/validator.py", line 266, in validate
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/words.py", line 20, in generate_corpus_id
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/words.py", line 15, in acceptable_adjectives
    FileNotFoundError: [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[W 17:15:31.968 NotebookApp] 500 PUT /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/contents/Curries.ipynb (117.196.252.225): Unexpected error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[W 17:15:31.969 NotebookApp] Unexpected error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[E 17:15:31.970 NotebookApp] {
      "Cookie": "username-hub-gke2-mybinder-org=\"2|1:0|10:1621183609|30:username-hub-gke2-mybinder-org|44:YWJjYjcwMmU4MGExNDVmMzk3OGI3ZjBlNmNhZThmNjM=|4e45eb32acba1f080bba177582f5c38822597a4ab96a64e906cca8c3b87a0607\"; _xsrf=2|34e9a513|5bd98113160380829d02d69d0fba51f4|1621183609",
      "Referer": "https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/Curries.ipynb",
      "Origin": "https://hub.gke2.mybinder.org",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|34e9a513|5bd98113160380829d02d69d0fba51f4|1621183609",
      "Content-Type": "application/json",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.5",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0",
      "Content-Length": "471",
      "X-Scheme": "https",
      "X-Forwarded-Port": "443,80",
      "X-Forwarded-Host": "hub.gke2.mybinder.org",
      "X-Forwarded-Proto": "https,http",
      "X-Forwarded-For": "117.196.252.225,::ffff:10.0.14.6",
      "X-Real-Ip": "117.196.252.225",
      "X-Request-Id": "2cc08685072d37d7738f9a8a4e822c2e",
      "Host": "hub.gke2.mybinder.org",
      "Connection": "close"
    }
[E 17:15:31.970 NotebookApp] 500 PUT /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/contents/Curries.ipynb (117.196.252.225) 25.700000ms referer=https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/Curries.ipynb
[W 17:15:35.212 NotebookApp] 404 DELETE /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/sessions/f7abf295-16b7-47a9-8a4e-870587c174c9 (117.196.252.225): Session not found: session_id='f7abf295-16b7-47a9-8a4e-870587c174c9'
[W 17:15:35.213 NotebookApp] Session not found: session_id='f7abf295-16b7-47a9-8a4e-870587c174c9'
[W 17:15:35.213 NotebookApp] 404 DELETE /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/sessions/f7abf295-16b7-47a9-8a4e-870587c174c9 (117.196.252.225) 2.040000ms referer=https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/Curries.ipynb
[I 17:15:35.492 NotebookApp] Kernel started: 416032de-3bc0-400f-ba66-891bafabe393, name: python3
[I 17:15:42.366 NotebookApp] Starting buffering for 416032de-3bc0-400f-ba66-891bafabe393:039f7ced0340467791a150053098d8ac
[W 17:15:51.423 NotebookApp] Notebook Matplotlib Exercises .ipynb is not trusted
[I 17:15:53.932 NotebookApp] Kernel started: 0d9483ab-2f9c-448c-adc0-3d11baab3cc1, name: python3
[W 17:26:14.761 NotebookApp] Culling 'idle' kernel 'python3' (416032de-3bc0-400f-ba66-891bafabe393) with 0 connections due to 638 seconds of inactivity.
[I 17:26:14.766 NotebookApp] Kernel shutdown: 416032de-3bc0-400f-ba66-891bafabe393
[W 17:26:15.070 NotebookApp] Culling 'idle' kernel 'python3' (0d9483ab-2f9c-448c-adc0-3d11baab3cc1) with 1 connections due to 619 seconds of inactivity.
[I 17:26:15.071 NotebookApp] Kernel shutdown: 0d9483ab-2f9c-448c-adc0-3d11baab3cc1
[W 17:26:15.665 NotebookApp] 410 DELETE /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/sessions/084421dd-30a2-45ad-bf47-11441b0443b6 (117.196.252.225): Kernel deleted before session
[W 17:26:15.665 NotebookApp] Kernel deleted before session
[W 17:26:15.666 NotebookApp] 410 DELETE /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/sessions/084421dd-30a2-45ad-bf47-11441b0443b6 (117.196.252.225) 2.180000ms referer=https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/Matplotlib%20Exercises%20.ipynb
[I 17:30:41.515 NotebookApp] Kernel started: f2921999-b4a8-457d-a7df-4dc6f2f07422, name: python3
[I 17:31:42.445 NotebookApp] Saving file at /Curries.ipynb
[E 17:31:42.454 NotebookApp] Error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
    Traceback (most recent call last):
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 477, in save
        self._save_notebook(os_path, nb)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 291, in _save_notebook
        nbformat.write(nb, f, version=nbformat.NO_CONVERT)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/__init__.py", line 164, in write
        return write(nb, f, version=version, **kwargs)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/__init__.py", line 107, in writes
        try:
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/validator.py", line 266, in validate
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/words.py", line 20, in generate_corpus_id
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/words.py", line 15, in acceptable_adjectives
    FileNotFoundError: [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[W 17:31:42.455 NotebookApp] 500 PUT /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/contents/Curries.ipynb (117.196.252.225): Unexpected error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[W 17:31:42.455 NotebookApp] Unexpected error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[E 17:31:42.456 NotebookApp] {
      "Cookie": "username-hub-gke2-mybinder-org=\"2|1:0|10:1621183609|30:username-hub-gke2-mybinder-org|44:YWJjYjcwMmU4MGExNDVmMzk3OGI3ZjBlNmNhZThmNjM=|4e45eb32acba1f080bba177582f5c38822597a4ab96a64e906cca8c3b87a0607\"; _xsrf=2|34e9a513|5bd98113160380829d02d69d0fba51f4|1621183609",
      "Referer": "https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/Curries.ipynb",
      "Origin": "https://hub.gke2.mybinder.org",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|34e9a513|5bd98113160380829d02d69d0fba51f4|1621183609",
      "Content-Type": "application/json",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.5",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0",
      "Content-Length": "1148",
      "X-Scheme": "https",
      "X-Forwarded-Port": "443,80",
      "X-Forwarded-Host": "hub.gke2.mybinder.org",
      "X-Forwarded-Proto": "https,http",
      "X-Forwarded-For": "117.196.252.225,::ffff:10.0.10.8",
      "X-Real-Ip": "117.196.252.225",
      "X-Request-Id": "6e52832bbddf863ee252471d73cb31a4",
      "Host": "hub.gke2.mybinder.org",
      "Connection": "close"
    }
[E 17:31:42.456 NotebookApp] 500 PUT /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/contents/Curries.ipynb (117.196.252.225) 12.240000ms referer=https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/Curries.ipynb
[I 17:32:39.656 NotebookApp] Saving file at /Curries.ipynb
[E 17:32:39.665 NotebookApp] Error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
    Traceback (most recent call last):
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 477, in save
        self._save_notebook(os_path, nb)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 291, in _save_notebook
        nbformat.write(nb, f, version=nbformat.NO_CONVERT)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/__init__.py", line 164, in write
        return write(nb, f, version=version, **kwargs)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/__init__.py", line 107, in writes
        try:
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/validator.py", line 266, in validate
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/words.py", line 20, in generate_corpus_id
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/words.py", line 15, in acceptable_adjectives
    FileNotFoundError: [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[W 17:32:39.666 NotebookApp] 500 PUT /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/contents/Curries.ipynb (117.196.252.225): Unexpected error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[W 17:32:39.666 NotebookApp] Unexpected error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[E 17:32:39.667 NotebookApp] {
      "Cookie": "username-hub-gke2-mybinder-org=\"2|1:0|10:1621183609|30:username-hub-gke2-mybinder-org|44:YWJjYjcwMmU4MGExNDVmMzk3OGI3ZjBlNmNhZThmNjM=|4e45eb32acba1f080bba177582f5c38822597a4ab96a64e906cca8c3b87a0607\"; _xsrf=2|34e9a513|5bd98113160380829d02d69d0fba51f4|1621183609",
      "Referer": "https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/Curries.ipynb",
      "Origin": "https://hub.gke2.mybinder.org",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|34e9a513|5bd98113160380829d02d69d0fba51f4|1621183609",
      "Content-Type": "application/json",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.5",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0",
      "Content-Length": "1342",
      "X-Scheme": "https",
      "X-Forwarded-Port": "443,80",
      "X-Forwarded-Host": "hub.gke2.mybinder.org",
      "X-Forwarded-Proto": "https,http",
      "X-Forwarded-For": "117.196.252.225,::ffff:10.0.10.8",
      "X-Real-Ip": "117.196.252.225",
      "X-Request-Id": "716bfe09ff2ac37059642f5771ac9320",
      "Host": "hub.gke2.mybinder.org",
      "Connection": "close"
    }
[E 17:32:39.667 NotebookApp] 500 PUT /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/contents/Curries.ipynb (117.196.252.225) 12.470000ms referer=https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/Curries.ipynb
[I 17:32:41.776 NotebookApp] Saving file at /Curries.ipynb
[E 17:32:41.786 NotebookApp] Error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
    Traceback (most recent call last):
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 477, in save
        self._save_notebook(os_path, nb)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 291, in _save_notebook
        nbformat.write(nb, f, version=nbformat.NO_CONVERT)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/__init__.py", line 164, in write
        return write(nb, f, version=version, **kwargs)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/__init__.py", line 107, in writes
        try:
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/validator.py", line 266, in validate
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/words.py", line 20, in generate_corpus_id
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/words.py", line 15, in acceptable_adjectives
    FileNotFoundError: [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[W 17:32:41.786 NotebookApp] 500 PUT /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/contents/Curries.ipynb (117.196.252.225): Unexpected error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[W 17:32:41.787 NotebookApp] Unexpected error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[E 17:32:41.787 NotebookApp] {
      "Cookie": "username-hub-gke2-mybinder-org=\"2|1:0|10:1621183609|30:username-hub-gke2-mybinder-org|44:YWJjYjcwMmU4MGExNDVmMzk3OGI3ZjBlNmNhZThmNjM=|4e45eb32acba1f080bba177582f5c38822597a4ab96a64e906cca8c3b87a0607\"; _xsrf=2|34e9a513|5bd98113160380829d02d69d0fba51f4|1621183609",
      "Referer": "https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/Curries.ipynb",
      "Origin": "https://hub.gke2.mybinder.org",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|34e9a513|5bd98113160380829d02d69d0fba51f4|1621183609",
      "Content-Type": "application/json",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.5",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0",
      "Content-Length": "1342",
      "X-Scheme": "https",
      "X-Forwarded-Port": "443,80",
      "X-Forwarded-Host": "hub.gke2.mybinder.org",
      "X-Forwarded-Proto": "https,http",
      "X-Forwarded-For": "117.196.252.225,::ffff:10.0.10.8",
      "X-Real-Ip": "117.196.252.225",
      "X-Request-Id": "de1e5567edc93b76ff898247de847a23",
      "Host": "hub.gke2.mybinder.org",
      "Connection": "close"
    }
[E 17:32:41.787 NotebookApp] 500 PUT /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/contents/Curries.ipynb (117.196.252.225) 12.290000ms referer=https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/Curries.ipynb
[I 17:34:33.383 NotebookApp] Saving file at /Curries.ipynb
[E 17:34:33.392 NotebookApp] Error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
    Traceback (most recent call last):
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 477, in save
        self._save_notebook(os_path, nb)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 291, in _save_notebook
        nbformat.write(nb, f, version=nbformat.NO_CONVERT)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/__init__.py", line 164, in write
        return write(nb, f, version=version, **kwargs)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/__init__.py", line 107, in writes
        try:
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/validator.py", line 266, in validate
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/words.py", line 20, in generate_corpus_id
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/words.py", line 15, in acceptable_adjectives
    FileNotFoundError: [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[W 17:34:33.393 NotebookApp] 500 PUT /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/contents/Curries.ipynb (117.196.252.225): Unexpected error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[W 17:34:33.393 NotebookApp] Unexpected error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[E 17:34:33.394 NotebookApp] {
      "Cookie": "username-hub-gke2-mybinder-org=\"2|1:0|10:1621183609|30:username-hub-gke2-mybinder-org|44:YWJjYjcwMmU4MGExNDVmMzk3OGI3ZjBlNmNhZThmNjM=|4e45eb32acba1f080bba177582f5c38822597a4ab96a64e906cca8c3b87a0607\"; _xsrf=2|34e9a513|5bd98113160380829d02d69d0fba51f4|1621183609",
      "Referer": "https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/Curries.ipynb",
      "Origin": "https://hub.gke2.mybinder.org",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|34e9a513|5bd98113160380829d02d69d0fba51f4|1621183609",
      "Content-Type": "application/json",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.5",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0",
      "Content-Length": "2342",
      "X-Scheme": "https",
      "X-Forwarded-Port": "443,80",
      "X-Forwarded-Host": "hub.gke2.mybinder.org",
      "X-Forwarded-Proto": "https,http",
      "X-Forwarded-For": "117.196.252.225,::ffff:10.0.10.8",
      "X-Real-Ip": "117.196.252.225",
      "X-Request-Id": "4558823fb8783f6df3ae9975d3ddf41b",
      "Host": "hub.gke2.mybinder.org",
      "Connection": "close"
    }
[E 17:34:33.394 NotebookApp] 500 PUT /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/contents/Curries.ipynb (117.196.252.225) 12.150000ms referer=https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/Curries.ipynb
[I 17:34:42.109 NotebookApp] Saving file at /Curries.ipynb
[E 17:34:42.123 NotebookApp] Error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
    Traceback (most recent call last):
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 477, in save
        self._save_notebook(os_path, nb)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 291, in _save_notebook
        nbformat.write(nb, f, version=nbformat.NO_CONVERT)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/__init__.py", line 164, in write
        return write(nb, f, version=version, **kwargs)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/__init__.py", line 107, in writes
        try:
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/validator.py", line 266, in validate
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/words.py", line 20, in generate_corpus_id
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/words.py", line 15, in acceptable_adjectives
    FileNotFoundError: [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[W 17:34:42.124 NotebookApp] 500 PUT /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/contents/Curries.ipynb (117.196.252.225): Unexpected error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[W 17:34:42.124 NotebookApp] Unexpected error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[E 17:34:42.125 NotebookApp] {
      "Cookie": "username-hub-gke2-mybinder-org=\"2|1:0|10:1621183609|30:username-hub-gke2-mybinder-org|44:YWJjYjcwMmU4MGExNDVmMzk3OGI3ZjBlNmNhZThmNjM=|4e45eb32acba1f080bba177582f5c38822597a4ab96a64e906cca8c3b87a0607\"; _xsrf=2|34e9a513|5bd98113160380829d02d69d0fba51f4|1621183609",
      "Referer": "https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/Curries.ipynb",
      "Origin": "https://hub.gke2.mybinder.org",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|34e9a513|5bd98113160380829d02d69d0fba51f4|1621183609",
      "Content-Type": "application/json",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.5",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0",
      "Content-Length": "2342",
      "X-Scheme": "https",
      "X-Forwarded-Port": "443,80",
      "X-Forwarded-Host": "hub.gke2.mybinder.org",
      "X-Forwarded-Proto": "https,http",
      "X-Forwarded-For": "117.196.252.225,::ffff:10.0.10.8",
      "X-Real-Ip": "117.196.252.225",
      "X-Request-Id": "969901b73158d3efb94195f32679d7e6",
      "Host": "hub.gke2.mybinder.org",
      "Connection": "close"
    }
[E 17:34:42.125 NotebookApp] 500 PUT /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/contents/Curries.ipynb (117.196.252.225) 16.720000ms referer=https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/Curries.ipynb
[I 17:35:13.839 NotebookApp] New terminal with automatic name: 2
TermSocket.open: 2
TermSocket.open: Opened 2
[I 17:36:41.814 NotebookApp] Saving file at /Curries.ipynb
[E 17:36:41.825 NotebookApp] Error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
    Traceback (most recent call last):
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 477, in save
        self._save_notebook(os_path, nb)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 291, in _save_notebook
        nbformat.write(nb, f, version=nbformat.NO_CONVERT)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/__init__.py", line 164, in write
        return write(nb, f, version=version, **kwargs)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/__init__.py", line 107, in writes
        try:
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/validator.py", line 266, in validate
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/words.py", line 20, in generate_corpus_id
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/words.py", line 15, in acceptable_adjectives
    FileNotFoundError: [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[W 17:36:41.826 NotebookApp] 500 PUT /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/contents/Curries.ipynb (117.196.252.225): Unexpected error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[W 17:36:41.826 NotebookApp] Unexpected error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[E 17:36:41.827 NotebookApp] {
      "Cookie": "username-hub-gke2-mybinder-org=\"2|1:0|10:1621183609|30:username-hub-gke2-mybinder-org|44:YWJjYjcwMmU4MGExNDVmMzk3OGI3ZjBlNmNhZThmNjM=|4e45eb32acba1f080bba177582f5c38822597a4ab96a64e906cca8c3b87a0607\"; _xsrf=2|34e9a513|5bd98113160380829d02d69d0fba51f4|1621183609",
      "Referer": "https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/Curries.ipynb",
      "Origin": "https://hub.gke2.mybinder.org",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|34e9a513|5bd98113160380829d02d69d0fba51f4|1621183609",
      "Content-Type": "application/json",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.5",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0",
      "Content-Length": "2342",
      "X-Scheme": "https",
      "X-Forwarded-Port": "443,80",
      "X-Forwarded-Host": "hub.gke2.mybinder.org",
      "X-Forwarded-Proto": "https,http",
      "X-Forwarded-For": "117.196.252.225,::ffff:10.0.10.8",
      "X-Real-Ip": "117.196.252.225",
      "X-Request-Id": "0de452eecfdef2f5dd1bb5396117baa6",
      "Host": "hub.gke2.mybinder.org",
      "Connection": "close"
    }
[E 17:36:41.827 NotebookApp] 500 PUT /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/contents/Curries.ipynb (117.196.252.225) 14.940000ms referer=https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/Curries.ipynb
[I 17:38:41.797 NotebookApp] Saving file at /Curries.ipynb
[E 17:38:41.809 NotebookApp] Error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
    Traceback (most recent call last):
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 477, in save
        self._save_notebook(os_path, nb)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 291, in _save_notebook
        nbformat.write(nb, f, version=nbformat.NO_CONVERT)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/__init__.py", line 164, in write
        return write(nb, f, version=version, **kwargs)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/__init__.py", line 107, in writes
        try:
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/validator.py", line 266, in validate
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/words.py", line 20, in generate_corpus_id
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/words.py", line 15, in acceptable_adjectives
    FileNotFoundError: [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[W 17:38:41.810 NotebookApp] 500 PUT /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/contents/Curries.ipynb (117.196.252.225): Unexpected error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[W 17:38:41.810 NotebookApp] Unexpected error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[E 17:38:41.811 NotebookApp] {
      "Cookie": "username-hub-gke2-mybinder-org=\"2|1:0|10:1621183609|30:username-hub-gke2-mybinder-org|44:YWJjYjcwMmU4MGExNDVmMzk3OGI3ZjBlNmNhZThmNjM=|4e45eb32acba1f080bba177582f5c38822597a4ab96a64e906cca8c3b87a0607\"; _xsrf=2|34e9a513|5bd98113160380829d02d69d0fba51f4|1621183609",
      "Referer": "https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/Curries.ipynb",
      "Origin": "https://hub.gke2.mybinder.org",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|34e9a513|5bd98113160380829d02d69d0fba51f4|1621183609",
      "Content-Type": "application/json",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.5",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0",
      "Content-Length": "2342",
      "X-Scheme": "https",
      "X-Forwarded-Port": "443,80",
      "X-Forwarded-Host": "hub.gke2.mybinder.org",
      "X-Forwarded-Proto": "https,http",
      "X-Forwarded-For": "117.196.252.225,::ffff:10.0.10.8",
      "X-Real-Ip": "117.196.252.225",
      "X-Request-Id": "9bb7f305a5eda05aced3fc5c69e02420",
      "Host": "hub.gke2.mybinder.org",
      "Connection": "close"
    }
[E 17:38:41.811 NotebookApp] 500 PUT /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/contents/Curries.ipynb (117.196.252.225) 14.550000ms referer=https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/Curries.ipynb
[I 17:39:14.620 NotebookApp] Starting buffering for f2921999-b4a8-457d-a7df-4dc6f2f07422:eb7e5d6889d44af08b246a7275ad0744
[I 17:39:35.121 NotebookApp] Saving file at /Curries.ipynb
[E 17:39:35.135 NotebookApp] Error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
    Traceback (most recent call last):
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 477, in save
        self._save_notebook(os_path, nb)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 291, in _save_notebook
        nbformat.write(nb, f, version=nbformat.NO_CONVERT)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/__init__.py", line 164, in write
        return write(nb, f, version=version, **kwargs)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/__init__.py", line 107, in writes
        try:
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/validator.py", line 266, in validate
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/words.py", line 20, in generate_corpus_id
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/words.py", line 15, in acceptable_adjectives
    FileNotFoundError: [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[W 17:39:35.136 NotebookApp] 500 PUT /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/contents/Curries.ipynb (117.196.252.225): Unexpected error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[W 17:39:35.136 NotebookApp] Unexpected error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[E 17:39:35.137 NotebookApp] {
      "Cookie": "username-hub-gke2-mybinder-org=\"2|1:0|10:1621183609|30:username-hub-gke2-mybinder-org|44:YWJjYjcwMmU4MGExNDVmMzk3OGI3ZjBlNmNhZThmNjM=|4e45eb32acba1f080bba177582f5c38822597a4ab96a64e906cca8c3b87a0607\"; _xsrf=2|34e9a513|5bd98113160380829d02d69d0fba51f4|1621183609",
      "Referer": "https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/Curries.ipynb",
      "Origin": "https://hub.gke2.mybinder.org",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|34e9a513|5bd98113160380829d02d69d0fba51f4|1621183609",
      "Content-Type": "application/json",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.5",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0",
      "Content-Length": "471",
      "X-Scheme": "https",
      "X-Forwarded-Port": "443,80",
      "X-Forwarded-Host": "hub.gke2.mybinder.org",
      "X-Forwarded-Proto": "https,http",
      "X-Forwarded-For": "117.196.252.225,::ffff:10.0.10.8",
      "X-Real-Ip": "117.196.252.225",
      "X-Request-Id": "6155b0b8640e8895211b007d5a9fbe08",
      "Host": "hub.gke2.mybinder.org",
      "Connection": "close"
    }
[E 17:39:35.137 NotebookApp] 500 PUT /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/contents/Curries.ipynb (117.196.252.225) 16.700000ms referer=https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/Curries.ipynb
[I 17:40:00.180 NotebookApp] Starting buffering for f2921999-b4a8-457d-a7df-4dc6f2f07422:df68cb18ffc049098b034c63690fbf25
[I 17:40:03.419 NotebookApp] Saving file at /Curries.ipynb
[E 17:40:03.426 NotebookApp] Error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
    Traceback (most recent call last):
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 477, in save
        self._save_notebook(os_path, nb)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 291, in _save_notebook
        nbformat.write(nb, f, version=nbformat.NO_CONVERT)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/__init__.py", line 164, in write
        return write(nb, f, version=version, **kwargs)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/__init__.py", line 107, in writes
        try:
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/validator.py", line 266, in validate
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/words.py", line 20, in generate_corpus_id
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/words.py", line 15, in acceptable_adjectives
    FileNotFoundError: [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[W 17:40:03.427 NotebookApp] 500 PUT /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/contents/Curries.ipynb (117.196.252.225): Unexpected error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[W 17:40:03.427 NotebookApp] Unexpected error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[E 17:40:03.428 NotebookApp] {
      "Cookie": "username-hub-gke2-mybinder-org=\"2|1:0|10:1621183609|30:username-hub-gke2-mybinder-org|44:YWJjYjcwMmU4MGExNDVmMzk3OGI3ZjBlNmNhZThmNjM=|4e45eb32acba1f080bba177582f5c38822597a4ab96a64e906cca8c3b87a0607\"; _xsrf=2|34e9a513|5bd98113160380829d02d69d0fba51f4|1621183609",
      "Referer": "https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/Curries.ipynb",
      "Origin": "https://hub.gke2.mybinder.org",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|34e9a513|5bd98113160380829d02d69d0fba51f4|1621183609",
      "Content-Type": "application/json",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.5",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0",
      "Content-Length": "261",
      "X-Scheme": "https",
      "X-Forwarded-Port": "443,80",
      "X-Forwarded-Host": "hub.gke2.mybinder.org",
      "X-Forwarded-Proto": "https,http",
      "X-Forwarded-For": "117.196.252.225,::ffff:10.0.10.8",
      "X-Real-Ip": "117.196.252.225",
      "X-Request-Id": "de5ac43f9bb5d4dd11cc2f1cd0985c04",
      "Host": "hub.gke2.mybinder.org",
      "Connection": "close"
    }
[E 17:40:03.428 NotebookApp] 500 PUT /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/contents/Curries.ipynb (117.196.252.225) 9.990000ms referer=https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/Curries.ipynb
[I 17:40:06.765 NotebookApp] Saving file at /Curries.ipynb
[E 17:40:06.778 NotebookApp] Error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
    Traceback (most recent call last):
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 477, in save
        self._save_notebook(os_path, nb)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 291, in _save_notebook
        nbformat.write(nb, f, version=nbformat.NO_CONVERT)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/__init__.py", line 164, in write
        return write(nb, f, version=version, **kwargs)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/__init__.py", line 107, in writes
        try:
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/validator.py", line 266, in validate
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/words.py", line 20, in generate_corpus_id
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/words.py", line 15, in acceptable_adjectives
    FileNotFoundError: [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[W 17:40:06.778 NotebookApp] 500 PUT /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/contents/Curries.ipynb (117.196.252.225): Unexpected error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[W 17:40:06.779 NotebookApp] Unexpected error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[E 17:40:06.779 NotebookApp] {
      "Cookie": "username-hub-gke2-mybinder-org=\"2|1:0|10:1621183609|30:username-hub-gke2-mybinder-org|44:YWJjYjcwMmU4MGExNDVmMzk3OGI3ZjBlNmNhZThmNjM=|4e45eb32acba1f080bba177582f5c38822597a4ab96a64e906cca8c3b87a0607\"; _xsrf=2|34e9a513|5bd98113160380829d02d69d0fba51f4|1621183609",
      "Referer": "https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/Curries.ipynb",
      "Origin": "https://hub.gke2.mybinder.org",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|34e9a513|5bd98113160380829d02d69d0fba51f4|1621183609",
      "Content-Type": "application/json",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.5",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0",
      "Content-Length": "471",
      "X-Scheme": "https",
      "X-Forwarded-Port": "443,80",
      "X-Forwarded-Host": "hub.gke2.mybinder.org",
      "X-Forwarded-Proto": "https,http",
      "X-Forwarded-For": "117.196.252.225,::ffff:10.0.10.8",
      "X-Real-Ip": "117.196.252.225",
      "X-Request-Id": "b94490d874496f0572c577881d96df90",
      "Host": "hub.gke2.mybinder.org",
      "Connection": "close"
    }
[E 17:40:06.780 NotebookApp] 500 PUT /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/contents/Curries.ipynb (117.196.252.225) 15.900000ms referer=https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/Curries.ipynb
[I 17:40:08.176 NotebookApp] Saving file at /Curries.ipynb
[E 17:40:08.188 NotebookApp] Error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
    Traceback (most recent call last):
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 477, in save
        self._save_notebook(os_path, nb)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 291, in _save_notebook
        nbformat.write(nb, f, version=nbformat.NO_CONVERT)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/__init__.py", line 164, in write
        return write(nb, f, version=version, **kwargs)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/__init__.py", line 107, in writes
        try:
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/validator.py", line 266, in validate
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/words.py", line 20, in generate_corpus_id
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/words.py", line 15, in acceptable_adjectives
    FileNotFoundError: [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[W 17:40:08.189 NotebookApp] 500 PUT /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/contents/Curries.ipynb (117.196.252.225): Unexpected error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[W 17:40:08.189 NotebookApp] Unexpected error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[E 17:40:08.190 NotebookApp] {
      "Cookie": "username-hub-gke2-mybinder-org=\"2|1:0|10:1621183609|30:username-hub-gke2-mybinder-org|44:YWJjYjcwMmU4MGExNDVmMzk3OGI3ZjBlNmNhZThmNjM=|4e45eb32acba1f080bba177582f5c38822597a4ab96a64e906cca8c3b87a0607\"; _xsrf=2|34e9a513|5bd98113160380829d02d69d0fba51f4|1621183609",
      "Referer": "https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/Curries.ipynb",
      "Origin": "https://hub.gke2.mybinder.org",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|34e9a513|5bd98113160380829d02d69d0fba51f4|1621183609",
      "Content-Type": "application/json",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.5",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0",
      "Content-Length": "471",
      "X-Scheme": "https",
      "X-Forwarded-Port": "443,80",
      "X-Forwarded-Host": "hub.gke2.mybinder.org",
      "X-Forwarded-Proto": "https,http",
      "X-Forwarded-For": "117.196.252.225,::ffff:10.0.10.8",
      "X-Real-Ip": "117.196.252.225",
      "X-Request-Id": "3d37197626264fe8f745f5e33f7ecdcb",
      "Host": "hub.gke2.mybinder.org",
      "Connection": "close"
    }
[E 17:40:08.190 NotebookApp] 500 PUT /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/contents/Curries.ipynb (117.196.252.225) 15.200000ms referer=https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/Curries.ipynb
[I 17:40:09.275 NotebookApp] Saving file at /Curries.ipynb
[E 17:40:09.285 NotebookApp] Error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
    Traceback (most recent call last):
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 477, in save
        self._save_notebook(os_path, nb)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 291, in _save_notebook
        nbformat.write(nb, f, version=nbformat.NO_CONVERT)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/__init__.py", line 164, in write
        return write(nb, f, version=version, **kwargs)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/__init__.py", line 107, in writes
        try:
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/validator.py", line 266, in validate
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/words.py", line 20, in generate_corpus_id
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/words.py", line 15, in acceptable_adjectives
    FileNotFoundError: [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[W 17:40:09.286 NotebookApp] 500 PUT /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/contents/Curries.ipynb (117.196.252.225): Unexpected error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[W 17:40:09.286 NotebookApp] Unexpected error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[E 17:40:09.287 NotebookApp] {
      "Cookie": "username-hub-gke2-mybinder-org=\"2|1:0|10:1621183609|30:username-hub-gke2-mybinder-org|44:YWJjYjcwMmU4MGExNDVmMzk3OGI3ZjBlNmNhZThmNjM=|4e45eb32acba1f080bba177582f5c38822597a4ab96a64e906cca8c3b87a0607\"; _xsrf=2|34e9a513|5bd98113160380829d02d69d0fba51f4|1621183609",
      "Referer": "https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/Curries.ipynb",
      "Origin": "https://hub.gke2.mybinder.org",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|34e9a513|5bd98113160380829d02d69d0fba51f4|1621183609",
      "Content-Type": "application/json",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.5",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0",
      "Content-Length": "471",
      "X-Scheme": "https",
      "X-Forwarded-Port": "443,80",
      "X-Forwarded-Host": "hub.gke2.mybinder.org",
      "X-Forwarded-Proto": "https,http",
      "X-Forwarded-For": "117.196.252.225,::ffff:10.0.10.8",
      "X-Real-Ip": "117.196.252.225",
      "X-Request-Id": "81824aa98fdcee54cd2ef4085e3dae3d",
      "Host": "hub.gke2.mybinder.org",
      "Connection": "close"
    }
[E 17:40:09.287 NotebookApp] 500 PUT /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/contents/Curries.ipynb (117.196.252.225) 12.180000ms referer=https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/Curries.ipynb
[I 17:40:09.491 NotebookApp] Saving file at /Curries.ipynb
[E 17:40:09.502 NotebookApp] Error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
    Traceback (most recent call last):
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 477, in save
        self._save_notebook(os_path, nb)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 291, in _save_notebook
        nbformat.write(nb, f, version=nbformat.NO_CONVERT)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/__init__.py", line 164, in write
        return write(nb, f, version=version, **kwargs)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/__init__.py", line 107, in writes
        try:
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/validator.py", line 266, in validate
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/words.py", line 20, in generate_corpus_id
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/words.py", line 15, in acceptable_adjectives
    FileNotFoundError: [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[W 17:40:09.502 NotebookApp] 500 PUT /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/contents/Curries.ipynb (117.196.252.225): Unexpected error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[W 17:40:09.503 NotebookApp] Unexpected error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[E 17:40:09.503 NotebookApp] {
      "Cookie": "username-hub-gke2-mybinder-org=\"2|1:0|10:1621183609|30:username-hub-gke2-mybinder-org|44:YWJjYjcwMmU4MGExNDVmMzk3OGI3ZjBlNmNhZThmNjM=|4e45eb32acba1f080bba177582f5c38822597a4ab96a64e906cca8c3b87a0607\"; _xsrf=2|34e9a513|5bd98113160380829d02d69d0fba51f4|1621183609",
      "Referer": "https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/Curries.ipynb",
      "Origin": "https://hub.gke2.mybinder.org",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|34e9a513|5bd98113160380829d02d69d0fba51f4|1621183609",
      "Content-Type": "application/json",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.5",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0",
      "Content-Length": "471",
      "X-Scheme": "https",
      "X-Forwarded-Port": "443,80",
      "X-Forwarded-Host": "hub.gke2.mybinder.org",
      "X-Forwarded-Proto": "https,http",
      "X-Forwarded-For": "117.196.252.225,::ffff:10.0.10.8",
      "X-Real-Ip": "117.196.252.225",
      "X-Request-Id": "e50acc16c83ba6a85e10cda0e6300757",
      "Host": "hub.gke2.mybinder.org",
      "Connection": "close"
    }
[E 17:40:09.503 NotebookApp] 500 PUT /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/contents/Curries.ipynb (117.196.252.225) 12.910000ms referer=https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/Curries.ipynb
[I 17:40:09.992 NotebookApp] Saving file at /Curries.ipynb
[E 17:40:10.002 NotebookApp] Error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
    Traceback (most recent call last):
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 477, in save
        self._save_notebook(os_path, nb)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 291, in _save_notebook
        nbformat.write(nb, f, version=nbformat.NO_CONVERT)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/__init__.py", line 164, in write
        return write(nb, f, version=version, **kwargs)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/__init__.py", line 107, in writes
        try:
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/validator.py", line 266, in validate
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/words.py", line 20, in generate_corpus_id
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/words.py", line 15, in acceptable_adjectives
    FileNotFoundError: [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[W 17:40:10.003 NotebookApp] 500 PUT /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/contents/Curries.ipynb (117.196.252.225): Unexpected error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[W 17:40:10.003 NotebookApp] Unexpected error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[E 17:40:10.004 NotebookApp] {
      "Cookie": "username-hub-gke2-mybinder-org=\"2|1:0|10:1621183609|30:username-hub-gke2-mybinder-org|44:YWJjYjcwMmU4MGExNDVmMzk3OGI3ZjBlNmNhZThmNjM=|4e45eb32acba1f080bba177582f5c38822597a4ab96a64e906cca8c3b87a0607\"; _xsrf=2|34e9a513|5bd98113160380829d02d69d0fba51f4|1621183609",
      "Referer": "https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/Curries.ipynb",
      "Origin": "https://hub.gke2.mybinder.org",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|34e9a513|5bd98113160380829d02d69d0fba51f4|1621183609",
      "Content-Type": "application/json",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.5",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0",
      "Content-Length": "471",
      "X-Scheme": "https",
      "X-Forwarded-Port": "443,80",
      "X-Forwarded-Host": "hub.gke2.mybinder.org",
      "X-Forwarded-Proto": "https,http",
      "X-Forwarded-For": "117.196.252.225,::ffff:10.0.10.8",
      "X-Real-Ip": "117.196.252.225",
      "X-Request-Id": "7043c6c7289d582412ecf790adf4e345",
      "Host": "hub.gke2.mybinder.org",
      "Connection": "close"
    }
[E 17:40:10.004 NotebookApp] 500 PUT /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/contents/Curries.ipynb (117.196.252.225) 13.090000ms referer=https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/Curries.ipynb
[I 17:40:52.609 NotebookApp] Creating new notebook in 
[I 17:40:54.329 NotebookApp] Kernel started: 99236206-1f85-48f7-98fe-e8b2a4b7bac4, name: python3
[I 17:41:19.138 NotebookApp] Saving file at /tut.ipynb
[E 17:41:19.150 NotebookApp] Error while saving file: tut.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
    Traceback (most recent call last):
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 477, in save
        self._save_notebook(os_path, nb)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 291, in _save_notebook
        nbformat.write(nb, f, version=nbformat.NO_CONVERT)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/__init__.py", line 164, in write
        return write(nb, f, version=version, **kwargs)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/__init__.py", line 107, in writes
        try:
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/validator.py", line 266, in validate
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/words.py", line 20, in generate_corpus_id
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/words.py", line 15, in acceptable_adjectives
    FileNotFoundError: [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[W 17:41:19.150 NotebookApp] 500 PUT /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/contents/tut.ipynb (117.196.252.225): Unexpected error while saving file: tut.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[W 17:41:19.151 NotebookApp] Unexpected error while saving file: tut.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[E 17:41:19.151 NotebookApp] {
      "Cookie": "username-hub-gke2-mybinder-org=\"2|1:0|10:1621183609|30:username-hub-gke2-mybinder-org|44:YWJjYjcwMmU4MGExNDVmMzk3OGI3ZjBlNmNhZThmNjM=|4e45eb32acba1f080bba177582f5c38822597a4ab96a64e906cca8c3b87a0607\"; _xsrf=2|34e9a513|5bd98113160380829d02d69d0fba51f4|1621183609",
      "Referer": "https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/tut.ipynb",
      "Origin": "https://hub.gke2.mybinder.org",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|34e9a513|5bd98113160380829d02d69d0fba51f4|1621183609",
      "Content-Type": "application/json",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.5",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0",
      "Content-Length": "471",
      "X-Scheme": "https",
      "X-Forwarded-Port": "443,80",
      "X-Forwarded-Host": "hub.gke2.mybinder.org",
      "X-Forwarded-Proto": "https,http",
      "X-Forwarded-For": "117.196.252.225,::ffff:10.0.10.8",
      "X-Real-Ip": "117.196.252.225",
      "X-Request-Id": "208e8fbaa182084d4113f720771b3827",
      "Host": "hub.gke2.mybinder.org",
      "Connection": "close"
    }
[E 17:41:19.151 NotebookApp] 500 PUT /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/contents/tut.ipynb (117.196.252.225) 13.710000ms referer=https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/tut.ipynb
[I 17:41:26.285 NotebookApp] Saving file at /tut.ipynb
[E 17:41:26.294 NotebookApp] Error while saving file: tut.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
    Traceback (most recent call last):
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 477, in save
        self._save_notebook(os_path, nb)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 291, in _save_notebook
        nbformat.write(nb, f, version=nbformat.NO_CONVERT)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/__init__.py", line 164, in write
        return write(nb, f, version=version, **kwargs)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/__init__.py", line 107, in writes
        try:
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/validator.py", line 266, in validate
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/words.py", line 20, in generate_corpus_id
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/words.py", line 15, in acceptable_adjectives
    FileNotFoundError: [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[W 17:41:26.295 NotebookApp] 500 PUT /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/contents/tut.ipynb (117.196.252.225): Unexpected error while saving file: tut.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[W 17:41:26.295 NotebookApp] Unexpected error while saving file: tut.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[E 17:41:26.296 NotebookApp] {
      "Cookie": "username-hub-gke2-mybinder-org=\"2|1:0|10:1621183609|30:username-hub-gke2-mybinder-org|44:YWJjYjcwMmU4MGExNDVmMzk3OGI3ZjBlNmNhZThmNjM=|4e45eb32acba1f080bba177582f5c38822597a4ab96a64e906cca8c3b87a0607\"; _xsrf=2|34e9a513|5bd98113160380829d02d69d0fba51f4|1621183609",
      "Referer": "https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/tut.ipynb",
      "Origin": "https://hub.gke2.mybinder.org",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|34e9a513|5bd98113160380829d02d69d0fba51f4|1621183609",
      "Content-Type": "application/json",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.5",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0",
      "Content-Length": "471",
      "X-Scheme": "https",
      "X-Forwarded-Port": "443,80",
      "X-Forwarded-Host": "hub.gke2.mybinder.org",
      "X-Forwarded-Proto": "https,http",
      "X-Forwarded-For": "117.196.252.225,::ffff:10.0.10.8",
      "X-Real-Ip": "117.196.252.225",
      "X-Request-Id": "c2bb9d2adbefcb4156ad2566f7f3bed0",
      "Host": "hub.gke2.mybinder.org",
      "Connection": "close"
    }
[E 17:41:26.296 NotebookApp] 500 PUT /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/contents/tut.ipynb (117.196.252.225) 12.390000ms referer=https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/tut.ipynb
[I 17:42:02.520 NotebookApp] Saving file at /Curries.ipynb
[E 17:42:02.532 NotebookApp] Error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
    Traceback (most recent call last):
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 477, in save
        self._save_notebook(os_path, nb)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 291, in _save_notebook
        nbformat.write(nb, f, version=nbformat.NO_CONVERT)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/__init__.py", line 164, in write
        return write(nb, f, version=version, **kwargs)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/__init__.py", line 107, in writes
        try:
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/validator.py", line 266, in validate
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/words.py", line 20, in generate_corpus_id
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/words.py", line 15, in acceptable_adjectives
    FileNotFoundError: [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[W 17:42:02.533 NotebookApp] 500 PUT /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/contents/Curries.ipynb (117.196.252.225): Unexpected error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[W 17:42:02.533 NotebookApp] Unexpected error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[E 17:42:02.534 NotebookApp] {
      "Cookie": "username-hub-gke2-mybinder-org=\"2|1:0|10:1621183609|30:username-hub-gke2-mybinder-org|44:YWJjYjcwMmU4MGExNDVmMzk3OGI3ZjBlNmNhZThmNjM=|4e45eb32acba1f080bba177582f5c38822597a4ab96a64e906cca8c3b87a0607\"; _xsrf=2|34e9a513|5bd98113160380829d02d69d0fba51f4|1621183609",
      "Referer": "https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/Curries.ipynb",
      "Origin": "https://hub.gke2.mybinder.org",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|34e9a513|5bd98113160380829d02d69d0fba51f4|1621183609",
      "Content-Type": "application/json",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.5",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0",
      "Content-Length": "471",
      "X-Scheme": "https",
      "X-Forwarded-Port": "443,80",
      "X-Forwarded-Host": "hub.gke2.mybinder.org",
      "X-Forwarded-Proto": "https,http",
      "X-Forwarded-For": "117.196.252.225,::ffff:10.0.10.8",
      "X-Real-Ip": "117.196.252.225",
      "X-Request-Id": "eb5121aad5144173ffedde0047fd56b8",
      "Host": "hub.gke2.mybinder.org",
      "Connection": "close"
    }
[E 17:42:02.534 NotebookApp] 500 PUT /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/contents/Curries.ipynb (117.196.252.225) 14.840000ms referer=https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/Curries.ipynb
[I 17:42:54.598 NotebookApp] Saving file at /tut.ipynb
[E 17:42:54.610 NotebookApp] Error while saving file: tut.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
    Traceback (most recent call last):
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 477, in save
        self._save_notebook(os_path, nb)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 291, in _save_notebook
        nbformat.write(nb, f, version=nbformat.NO_CONVERT)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/__init__.py", line 164, in write
        return write(nb, f, version=version, **kwargs)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/__init__.py", line 107, in writes
        try:
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/validator.py", line 266, in validate
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/words.py", line 20, in generate_corpus_id
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/words.py", line 15, in acceptable_adjectives
    FileNotFoundError: [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[W 17:42:54.610 NotebookApp] 500 PUT /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/contents/tut.ipynb (117.196.252.225): Unexpected error while saving file: tut.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[W 17:42:54.611 NotebookApp] Unexpected error while saving file: tut.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[E 17:42:54.612 NotebookApp] {
      "Cookie": "username-hub-gke2-mybinder-org=\"2|1:0|10:1621183609|30:username-hub-gke2-mybinder-org|44:YWJjYjcwMmU4MGExNDVmMzk3OGI3ZjBlNmNhZThmNjM=|4e45eb32acba1f080bba177582f5c38822597a4ab96a64e906cca8c3b87a0607\"; _xsrf=2|34e9a513|5bd98113160380829d02d69d0fba51f4|1621183609",
      "Referer": "https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/tut.ipynb",
      "Origin": "https://hub.gke2.mybinder.org",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|34e9a513|5bd98113160380829d02d69d0fba51f4|1621183609",
      "Content-Type": "application/json",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.5",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0",
      "Content-Length": "471",
      "X-Scheme": "https",
      "X-Forwarded-Port": "443,80",
      "X-Forwarded-Host": "hub.gke2.mybinder.org",
      "X-Forwarded-Proto": "https,http",
      "X-Forwarded-For": "117.196.252.225,::ffff:10.0.10.8",
      "X-Real-Ip": "117.196.252.225",
      "X-Request-Id": "4a317fcd69b79544b7d2f072af023415",
      "Host": "hub.gke2.mybinder.org",
      "Connection": "close"
    }
[E 17:42:54.612 NotebookApp] 500 PUT /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/contents/tut.ipynb (117.196.252.225) 14.250000ms referer=https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/tut.ipynb
[I 17:44:02.535 NotebookApp] Saving file at /Curries.ipynb
[E 17:44:02.549 NotebookApp] Error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
    Traceback (most recent call last):
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 477, in save
        self._save_notebook(os_path, nb)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 291, in _save_notebook
        nbformat.write(nb, f, version=nbformat.NO_CONVERT)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/__init__.py", line 164, in write
        return write(nb, f, version=version, **kwargs)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/__init__.py", line 107, in writes
        try:
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/validator.py", line 266, in validate
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/words.py", line 20, in generate_corpus_id
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/words.py", line 15, in acceptable_adjectives
    FileNotFoundError: [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[W 17:44:02.550 NotebookApp] 500 PUT /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/contents/Curries.ipynb (117.196.252.225): Unexpected error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[W 17:44:02.550 NotebookApp] Unexpected error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[E 17:44:02.551 NotebookApp] {
      "Cookie": "username-hub-gke2-mybinder-org=\"2|1:0|10:1621183609|30:username-hub-gke2-mybinder-org|44:YWJjYjcwMmU4MGExNDVmMzk3OGI3ZjBlNmNhZThmNjM=|4e45eb32acba1f080bba177582f5c38822597a4ab96a64e906cca8c3b87a0607\"; _xsrf=2|34e9a513|5bd98113160380829d02d69d0fba51f4|1621183609",
      "Referer": "https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/Curries.ipynb",
      "Origin": "https://hub.gke2.mybinder.org",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|34e9a513|5bd98113160380829d02d69d0fba51f4|1621183609",
      "Content-Type": "application/json",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.5",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0",
      "Content-Length": "471",
      "X-Scheme": "https",
      "X-Forwarded-Port": "443,80",
      "X-Forwarded-Host": "hub.gke2.mybinder.org",
      "X-Forwarded-Proto": "https,http",
      "X-Forwarded-For": "117.196.252.225,::ffff:10.0.10.8",
      "X-Real-Ip": "117.196.252.225",
      "X-Request-Id": "0ecbb9d3f6a545f66c8188dd21b5d7fe",
      "Host": "hub.gke2.mybinder.org",
      "Connection": "close"
    }
[E 17:44:02.551 NotebookApp] 500 PUT /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/contents/Curries.ipynb (117.196.252.225) 17.700000ms referer=https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/Curries.ipynb
[I 17:44:14.819 NotebookApp] Saving file at /tut.ipynb
[E 17:44:14.827 NotebookApp] Error while saving file: tut.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
    Traceback (most recent call last):
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 477, in save
        self._save_notebook(os_path, nb)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 291, in _save_notebook
        nbformat.write(nb, f, version=nbformat.NO_CONVERT)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/__init__.py", line 164, in write
        return write(nb, f, version=version, **kwargs)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/__init__.py", line 107, in writes
        try:
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/validator.py", line 266, in validate
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/words.py", line 20, in generate_corpus_id
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/words.py", line 15, in acceptable_adjectives
    FileNotFoundError: [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[W 17:44:14.828 NotebookApp] 500 PUT /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/contents/tut.ipynb (117.196.252.225): Unexpected error while saving file: tut.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[W 17:44:14.829 NotebookApp] Unexpected error while saving file: tut.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[E 17:44:14.830 NotebookApp] {
      "Cookie": "username-hub-gke2-mybinder-org=\"2|1:0|10:1621183609|30:username-hub-gke2-mybinder-org|44:YWJjYjcwMmU4MGExNDVmMzk3OGI3ZjBlNmNhZThmNjM=|4e45eb32acba1f080bba177582f5c38822597a4ab96a64e906cca8c3b87a0607\"; _xsrf=2|34e9a513|5bd98113160380829d02d69d0fba51f4|1621183609",
      "Referer": "https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/tut.ipynb",
      "Origin": "https://hub.gke2.mybinder.org",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|34e9a513|5bd98113160380829d02d69d0fba51f4|1621183609",
      "Content-Type": "application/json",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.5",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0",
      "Content-Length": "665",
      "X-Scheme": "https",
      "X-Forwarded-Port": "443,80",
      "X-Forwarded-Host": "hub.gke2.mybinder.org",
      "X-Forwarded-Proto": "https,http",
      "X-Forwarded-For": "117.196.252.225,::ffff:10.0.10.8",
      "X-Real-Ip": "117.196.252.225",
      "X-Request-Id": "5da14647dcd7638d58c71ff1e1637706",
      "Host": "hub.gke2.mybinder.org",
      "Connection": "close"
    }
[E 17:44:14.830 NotebookApp] 500 PUT /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/contents/tut.ipynb (117.196.252.225) 11.960000ms referer=https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/tut.ipynb
[I 17:44:33.765 NotebookApp] Kernel shutdown: 99236206-1f85-48f7-98fe-e8b2a4b7bac4
[W 17:44:34.356 NotebookApp] 404 DELETE /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/sessions/46c6de72-4984-474a-accf-46789c70dd30 (117.196.252.225): Session not found: session_id='46c6de72-4984-474a-accf-46789c70dd30'
[W 17:44:34.356 NotebookApp] Session not found: session_id='46c6de72-4984-474a-accf-46789c70dd30'
[W 17:44:34.357 NotebookApp] 404 DELETE /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/sessions/46c6de72-4984-474a-accf-46789c70dd30 (117.196.252.225) 1.860000ms referer=https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/tut.ipynb
[I 17:44:37.889 NotebookApp] Kernel shutdown: f2921999-b4a8-457d-a7df-4dc6f2f07422
[W 17:44:38.473 NotebookApp] 404 DELETE /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/sessions/a6250013-eec1-4db2-90bf-3a75dfddfb32 (117.196.252.225): Session not found: session_id='a6250013-eec1-4db2-90bf-3a75dfddfb32'
[W 17:44:38.473 NotebookApp] Session not found: session_id='a6250013-eec1-4db2-90bf-3a75dfddfb32'
[W 17:44:38.474 NotebookApp] 404 DELETE /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/sessions/a6250013-eec1-4db2-90bf-3a75dfddfb32 (117.196.252.225) 2.080000ms referer=https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/Curries.ipynb
[I 17:44:54.610 NotebookApp] Saving file at /tut.ipynb
[E 17:44:54.622 NotebookApp] Error while saving file: tut.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
    Traceback (most recent call last):
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 477, in save
        self._save_notebook(os_path, nb)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 291, in _save_notebook
        nbformat.write(nb, f, version=nbformat.NO_CONVERT)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/__init__.py", line 164, in write
        return write(nb, f, version=version, **kwargs)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/__init__.py", line 107, in writes
        try:
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/validator.py", line 266, in validate
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/words.py", line 20, in generate_corpus_id
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/words.py", line 15, in acceptable_adjectives
    FileNotFoundError: [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[W 17:44:54.622 NotebookApp] 500 PUT /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/contents/tut.ipynb (117.196.252.225): Unexpected error while saving file: tut.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[W 17:44:54.623 NotebookApp] Unexpected error while saving file: tut.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[E 17:44:54.623 NotebookApp] {
      "Cookie": "username-hub-gke2-mybinder-org=\"2|1:0|10:1621183609|30:username-hub-gke2-mybinder-org|44:YWJjYjcwMmU4MGExNDVmMzk3OGI3ZjBlNmNhZThmNjM=|4e45eb32acba1f080bba177582f5c38822597a4ab96a64e906cca8c3b87a0607\"; _xsrf=2|34e9a513|5bd98113160380829d02d69d0fba51f4|1621183609",
      "Referer": "https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/tut.ipynb",
      "Origin": "https://hub.gke2.mybinder.org",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|34e9a513|5bd98113160380829d02d69d0fba51f4|1621183609",
      "Content-Type": "application/json",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.5",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0",
      "Content-Length": "665",
      "X-Scheme": "https",
      "X-Forwarded-Port": "443,80",
      "X-Forwarded-Host": "hub.gke2.mybinder.org",
      "X-Forwarded-Proto": "https,http",
      "X-Forwarded-For": "117.196.252.225,::ffff:10.0.10.8",
      "X-Real-Ip": "117.196.252.225",
      "X-Request-Id": "9b3215d43496f6edd027d512b366e898",
      "Host": "hub.gke2.mybinder.org",
      "Connection": "close"
    }
[E 17:44:54.624 NotebookApp] 500 PUT /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/contents/tut.ipynb (117.196.252.225) 14.870000ms referer=https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/tut.ipynb
[W 17:45:11.072 NotebookApp] 404 DELETE /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/sessions/46c6de72-4984-474a-accf-46789c70dd30 (117.196.252.225): Session not found: session_id='46c6de72-4984-474a-accf-46789c70dd30'
[W 17:45:11.072 NotebookApp] Session not found: session_id='46c6de72-4984-474a-accf-46789c70dd30'
[W 17:45:11.073 NotebookApp] 404 DELETE /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/sessions/46c6de72-4984-474a-accf-46789c70dd30 (117.196.252.225) 2.140000ms referer=https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/tut.ipynb
[I 17:45:11.353 NotebookApp] Kernel started: 5c93a30c-2907-41f0-bf74-ba433adc3d67, name: python3
[I 17:45:24.450 NotebookApp] Starting buffering for 5c93a30c-2907-41f0-bf74-ba433adc3d67:c2912fe4d9fa4614a3f9127f1fdd8c63
[I 17:45:25.005 NotebookApp] Restoring connection for 5c93a30c-2907-41f0-bf74-ba433adc3d67:c2912fe4d9fa4614a3f9127f1fdd8c63
[I 17:45:46.093 NotebookApp] Starting buffering for 5c93a30c-2907-41f0-bf74-ba433adc3d67:c2912fe4d9fa4614a3f9127f1fdd8c63
[I 17:45:46.406 NotebookApp] Kernel restarted: 5c93a30c-2907-41f0-bf74-ba433adc3d67
[I 17:45:47.218 NotebookApp] Restoring connection for 5c93a30c-2907-41f0-bf74-ba433adc3d67:c2912fe4d9fa4614a3f9127f1fdd8c63
[I 17:45:47.223 NotebookApp] Replaying 6 buffered messages
[I 17:46:02.560 NotebookApp] Saving file at /Curries.ipynb
[E 17:46:02.573 NotebookApp] Error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
    Traceback (most recent call last):
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 477, in save
        self._save_notebook(os_path, nb)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 291, in _save_notebook
        nbformat.write(nb, f, version=nbformat.NO_CONVERT)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/__init__.py", line 164, in write
        return write(nb, f, version=version, **kwargs)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/__init__.py", line 107, in writes
        try:
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/validator.py", line 266, in validate
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/words.py", line 20, in generate_corpus_id
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/words.py", line 15, in acceptable_adjectives
    FileNotFoundError: [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[W 17:46:02.574 NotebookApp] 500 PUT /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/contents/Curries.ipynb (117.196.252.225): Unexpected error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[W 17:46:02.574 NotebookApp] Unexpected error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[E 17:46:02.575 NotebookApp] {
      "Cookie": "username-hub-gke2-mybinder-org=\"2|1:0|10:1621183609|30:username-hub-gke2-mybinder-org|44:YWJjYjcwMmU4MGExNDVmMzk3OGI3ZjBlNmNhZThmNjM=|4e45eb32acba1f080bba177582f5c38822597a4ab96a64e906cca8c3b87a0607\"; _xsrf=2|34e9a513|5bd98113160380829d02d69d0fba51f4|1621183609",
      "Referer": "https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/Curries.ipynb",
      "Origin": "https://hub.gke2.mybinder.org",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|34e9a513|5bd98113160380829d02d69d0fba51f4|1621183609",
      "Content-Type": "application/json",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.5",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0",
      "Content-Length": "471",
      "X-Scheme": "https",
      "X-Forwarded-Port": "443,80",
      "X-Forwarded-Host": "hub.gke2.mybinder.org",
      "X-Forwarded-Proto": "https,http",
      "X-Forwarded-For": "117.196.252.225,::ffff:10.0.10.8",
      "X-Real-Ip": "117.196.252.225",
      "X-Request-Id": "e8fed408837d1f1f2ba089756a3a596b",
      "Host": "hub.gke2.mybinder.org",
      "Connection": "close"
    }
[E 17:46:02.575 NotebookApp] 500 PUT /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/contents/Curries.ipynb (117.196.252.225) 15.740000ms referer=https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/Curries.ipynb
[I 17:46:54.634 NotebookApp] Saving file at /tut.ipynb
[E 17:46:54.648 NotebookApp] Error while saving file: tut.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
    Traceback (most recent call last):
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 477, in save
        self._save_notebook(os_path, nb)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 291, in _save_notebook
        nbformat.write(nb, f, version=nbformat.NO_CONVERT)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/__init__.py", line 164, in write
        return write(nb, f, version=version, **kwargs)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/__init__.py", line 107, in writes
        try:
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/validator.py", line 266, in validate
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/words.py", line 20, in generate_corpus_id
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/words.py", line 15, in acceptable_adjectives
    FileNotFoundError: [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[W 17:46:54.648 NotebookApp] 500 PUT /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/contents/tut.ipynb (117.196.252.225): Unexpected error while saving file: tut.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[W 17:46:54.648 NotebookApp] Unexpected error while saving file: tut.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[E 17:46:54.649 NotebookApp] {
      "Cookie": "username-hub-gke2-mybinder-org=\"2|1:0|10:1621183609|30:username-hub-gke2-mybinder-org|44:YWJjYjcwMmU4MGExNDVmMzk3OGI3ZjBlNmNhZThmNjM=|4e45eb32acba1f080bba177582f5c38822597a4ab96a64e906cca8c3b87a0607\"; _xsrf=2|34e9a513|5bd98113160380829d02d69d0fba51f4|1621183609",
      "Referer": "https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/tut.ipynb",
      "Origin": "https://hub.gke2.mybinder.org",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|34e9a513|5bd98113160380829d02d69d0fba51f4|1621183609",
      "Content-Type": "application/json",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.5",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0",
      "Content-Length": "665",
      "X-Scheme": "https",
      "X-Forwarded-Port": "443,80",
      "X-Forwarded-Host": "hub.gke2.mybinder.org",
      "X-Forwarded-Proto": "https,http",
      "X-Forwarded-For": "117.196.252.225,::ffff:10.0.10.8",
      "X-Real-Ip": "117.196.252.225",
      "X-Request-Id": "0545f90eb9e73567de65e7ffb72cf7c1",
      "Host": "hub.gke2.mybinder.org",
      "Connection": "close"
    }
[E 17:46:54.649 NotebookApp] 500 PUT /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/contents/tut.ipynb (117.196.252.225) 15.580000ms referer=https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/tut.ipynb
[I 17:48:01.251 NotebookApp] Saving file at /tut.ipynb
[E 17:48:01.270 NotebookApp] Error while saving file: tut.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
    Traceback (most recent call last):
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 477, in save
        self._save_notebook(os_path, nb)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 291, in _save_notebook
        nbformat.write(nb, f, version=nbformat.NO_CONVERT)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/__init__.py", line 164, in write
        return write(nb, f, version=version, **kwargs)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/__init__.py", line 107, in writes
        try:
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/validator.py", line 266, in validate
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/words.py", line 20, in generate_corpus_id
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/words.py", line 15, in acceptable_adjectives
    FileNotFoundError: [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[W 17:48:01.271 NotebookApp] 500 PUT /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/contents/tut.ipynb (117.196.252.225): Unexpected error while saving file: tut.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[W 17:48:01.272 NotebookApp] Unexpected error while saving file: tut.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[E 17:48:01.273 NotebookApp] {
      "Cookie": "username-hub-gke2-mybinder-org=\"2|1:0|10:1621183609|30:username-hub-gke2-mybinder-org|44:YWJjYjcwMmU4MGExNDVmMzk3OGI3ZjBlNmNhZThmNjM=|4e45eb32acba1f080bba177582f5c38822597a4ab96a64e906cca8c3b87a0607\"; _xsrf=2|34e9a513|5bd98113160380829d02d69d0fba51f4|1621183609",
      "Referer": "https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/tut.ipynb",
      "Origin": "https://hub.gke2.mybinder.org",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|34e9a513|5bd98113160380829d02d69d0fba51f4|1621183609",
      "Content-Type": "application/json",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.5",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0",
      "Content-Length": "665",
      "X-Scheme": "https",
      "X-Forwarded-Port": "443,80",
      "X-Forwarded-Host": "hub.gke2.mybinder.org",
      "X-Forwarded-Proto": "https,http",
      "X-Forwarded-For": "117.196.252.225,::ffff:10.0.10.8",
      "X-Real-Ip": "117.196.252.225",
      "X-Request-Id": "437f1fa5f9f16e4a32fe9159c900d3ce",
      "Host": "hub.gke2.mybinder.org",
      "Connection": "close"
    }
[E 17:48:01.274 NotebookApp] 500 PUT /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/contents/tut.ipynb (117.196.252.225) 23.720000ms referer=https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/tut.ipynb
[I 17:48:02.552 NotebookApp] Saving file at /Curries.ipynb
[E 17:48:02.577 NotebookApp] Error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
    Traceback (most recent call last):
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 477, in save
        self._save_notebook(os_path, nb)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 291, in _save_notebook
        nbformat.write(nb, f, version=nbformat.NO_CONVERT)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/__init__.py", line 164, in write
        return write(nb, f, version=version, **kwargs)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/__init__.py", line 107, in writes
        try:
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/validator.py", line 266, in validate
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/words.py", line 20, in generate_corpus_id
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/words.py", line 15, in acceptable_adjectives
    FileNotFoundError: [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[W 17:48:02.578 NotebookApp] 500 PUT /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/contents/Curries.ipynb (117.196.252.225): Unexpected error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[W 17:48:02.578 NotebookApp] Unexpected error while saving file: Curries.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[E 17:48:02.580 NotebookApp] {
      "Cookie": "username-hub-gke2-mybinder-org=\"2|1:0|10:1621183609|30:username-hub-gke2-mybinder-org|44:YWJjYjcwMmU4MGExNDVmMzk3OGI3ZjBlNmNhZThmNjM=|4e45eb32acba1f080bba177582f5c38822597a4ab96a64e906cca8c3b87a0607\"; _xsrf=2|34e9a513|5bd98113160380829d02d69d0fba51f4|1621183609",
      "Referer": "https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/Curries.ipynb",
      "Origin": "https://hub.gke2.mybinder.org",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|34e9a513|5bd98113160380829d02d69d0fba51f4|1621183609",
      "Content-Type": "application/json",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.5",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0",
      "Content-Length": "471",
      "X-Scheme": "https",
      "X-Forwarded-Port": "443,80",
      "X-Forwarded-Host": "hub.gke2.mybinder.org",
      "X-Forwarded-Proto": "https,http",
      "X-Forwarded-For": "117.196.252.225,::ffff:10.0.10.8",
      "X-Real-Ip": "117.196.252.225",
      "X-Request-Id": "08f0b3c4ecc330d2548b9ec034a5ebca",
      "Host": "hub.gke2.mybinder.org",
      "Connection": "close"
    }
[E 17:48:02.580 NotebookApp] 500 PUT /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/contents/Curries.ipynb (117.196.252.225) 29.530000ms referer=https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/Curries.ipynb
[I 17:48:08.227 NotebookApp] Starting buffering for 5c93a30c-2907-41f0-bf74-ba433adc3d67:c2912fe4d9fa4614a3f9127f1fdd8c63
[I 17:48:19.272 NotebookApp] Starting buffering for 5c93a30c-2907-41f0-bf74-ba433adc3d67:fc2c15d7ec394c3c8a75dd52d37fb3a4
[I 17:48:19.817 NotebookApp] Restoring connection for 5c93a30c-2907-41f0-bf74-ba433adc3d67:fc2c15d7ec394c3c8a75dd52d37fb3a4
[I 17:48:23.595 NotebookApp] Saving file at /tut.ipynb
[E 17:48:23.616 NotebookApp] Error while saving file: tut.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
    Traceback (most recent call last):
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 477, in save
        self._save_notebook(os_path, nb)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 291, in _save_notebook
        nbformat.write(nb, f, version=nbformat.NO_CONVERT)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/__init__.py", line 164, in write
        return write(nb, f, version=version, **kwargs)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/__init__.py", line 107, in writes
        try:
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/validator.py", line 266, in validate
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/words.py", line 20, in generate_corpus_id
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/words.py", line 15, in acceptable_adjectives
    FileNotFoundError: [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[W 17:48:23.618 NotebookApp] 500 PUT /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/contents/tut.ipynb (117.196.252.225): Unexpected error while saving file: tut.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[W 17:48:23.621 NotebookApp] Unexpected error while saving file: tut.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[E 17:48:23.622 NotebookApp] {
      "Cookie": "username-hub-gke2-mybinder-org=\"2|1:0|10:1621183609|30:username-hub-gke2-mybinder-org|44:YWJjYjcwMmU4MGExNDVmMzk3OGI3ZjBlNmNhZThmNjM=|4e45eb32acba1f080bba177582f5c38822597a4ab96a64e906cca8c3b87a0607\"; _xsrf=2|34e9a513|5bd98113160380829d02d69d0fba51f4|1621183609",
      "Referer": "https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/tut.ipynb",
      "Origin": "https://hub.gke2.mybinder.org",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|34e9a513|5bd98113160380829d02d69d0fba51f4|1621183609",
      "Content-Type": "application/json",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.5",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0",
      "Content-Length": "471",
      "X-Scheme": "https",
      "X-Forwarded-Port": "443,80",
      "X-Forwarded-Host": "hub.gke2.mybinder.org",
      "X-Forwarded-Proto": "https,http",
      "X-Forwarded-For": "117.196.252.225,::ffff:10.0.10.8",
      "X-Real-Ip": "117.196.252.225",
      "X-Request-Id": "b22ca6077c5a9bf74cc867c98878aa8a",
      "Host": "hub.gke2.mybinder.org",
      "Connection": "close"
    }
[E 17:48:23.622 NotebookApp] 500 PUT /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/contents/tut.ipynb (117.196.252.225) 27.630000ms referer=https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/tut.ipynb
[W 17:49:14.468 NotebookApp] 404 GET /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/contents/a.ipynb?type=notebook&content=0&_=1621187289664 (117.196.252.225): No such file or directory: a.ipynb
[W 17:49:14.469 NotebookApp] No such file or directory: a.ipynb
[W 17:49:14.469 NotebookApp] 404 GET /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/contents/a.ipynb?type=notebook&content=0&_=1621187289664 (117.196.252.225) 2.360000ms referer=https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/tut.ipynb
[I 17:49:14.732 NotebookApp] Uploading file to /a.ipynb
[E 17:49:14.745 NotebookApp] Error while saving file: a.ipynb [Errno 2] No such file or directory: '/home/jovyan/.~a.ipynb' -> '/home/jovyan/a.ipynb'
    Traceback (most recent call last):
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 110, in atomic_writing
        yield fileobj
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 211, in atomic_writing
        yield f
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 291, in _save_notebook
        nbformat.write(nb, f, version=nbformat.NO_CONVERT)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/__init__.py", line 164, in write
        return write(nb, f, version=version, **kwargs)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/__init__.py", line 107, in writes
        try:
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/validator.py", line 266, in validate
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/words.py", line 20, in generate_corpus_id
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/words.py", line 15, in acceptable_adjectives
    FileNotFoundError: [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 477, in save
        self._save_notebook(os_path, nb)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 291, in _save_notebook
        nbformat.write(nb, f, version=nbformat.NO_CONVERT)
      File "/srv/conda/envs/notebook/lib/python3.7/contextlib.py", line 130, in __exit__
        self.gen.throw(type, value, traceback)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 211, in atomic_writing
        yield f
      File "/srv/conda/envs/notebook/lib/python3.7/contextlib.py", line 130, in __exit__
        self.gen.throw(type, value, traceback)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 114, in atomic_writing
        replace_file(tmp_path, path)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 36, in replace_file
        os.replace(src, dst)
    FileNotFoundError: [Errno 2] No such file or directory: '/home/jovyan/.~a.ipynb' -> '/home/jovyan/a.ipynb'
[W 17:49:14.748 NotebookApp] 500 PUT /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/contents/a.ipynb (117.196.252.225): Unexpected error while saving file: a.ipynb [Errno 2] No such file or directory: '/home/jovyan/.~a.ipynb' -> '/home/jovyan/a.ipynb'
[W 17:49:14.748 NotebookApp] Unexpected error while saving file: a.ipynb [Errno 2] No such file or directory: '/home/jovyan/.~a.ipynb' -> '/home/jovyan/a.ipynb'
[E 17:49:14.749 NotebookApp] {
      "Cookie": "username-hub-gke2-mybinder-org=\"2|1:0|10:1621183609|30:username-hub-gke2-mybinder-org|44:YWJjYjcwMmU4MGExNDVmMzk3OGI3ZjBlNmNhZThmNjM=|4e45eb32acba1f080bba177582f5c38822597a4ab96a64e906cca8c3b87a0607\"; _xsrf=2|34e9a513|5bd98113160380829d02d69d0fba51f4|1621183609",
      "Referer": "https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/tut.ipynb",
      "Origin": "https://hub.gke2.mybinder.org",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|34e9a513|5bd98113160380829d02d69d0fba51f4|1621183609",
      "Content-Type": "application/json",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.5",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0",
      "Content-Length": "488",
      "X-Scheme": "https",
      "X-Forwarded-Port": "443,80",
      "X-Forwarded-Host": "hub.gke2.mybinder.org",
      "X-Forwarded-Proto": "https,http",
      "X-Forwarded-For": "117.196.252.225,::ffff:10.0.10.8",
      "X-Real-Ip": "117.196.252.225",
      "X-Request-Id": "7bb788d9936e74a097ae0bbe8ab25c64",
      "Host": "hub.gke2.mybinder.org",
      "Connection": "close"
    }
[E 17:49:14.749 NotebookApp] 500 PUT /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/contents/a.ipynb (117.196.252.225) 18.070000ms referer=https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/tut.ipynb
[I 17:49:40.271 NotebookApp] Saving file at /tut.ipynb
[E 17:49:40.312 NotebookApp] Error while saving file: tut.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
    Traceback (most recent call last):
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 477, in save
        self._save_notebook(os_path, nb)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 291, in _save_notebook
        nbformat.write(nb, f, version=nbformat.NO_CONVERT)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/__init__.py", line 164, in write
        return write(nb, f, version=version, **kwargs)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/__init__.py", line 107, in writes
        try:
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/validator.py", line 266, in validate
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/words.py", line 20, in generate_corpus_id
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/words.py", line 15, in acceptable_adjectives
    FileNotFoundError: [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[W 17:49:40.313 NotebookApp] 500 PUT /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/contents/tut.ipynb (117.196.252.225): Unexpected error while saving file: tut.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[W 17:49:40.313 NotebookApp] Unexpected error while saving file: tut.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[E 17:49:40.314 NotebookApp] {
      "Cookie": "username-hub-gke2-mybinder-org=\"2|1:0|10:1621183609|30:username-hub-gke2-mybinder-org|44:YWJjYjcwMmU4MGExNDVmMzk3OGI3ZjBlNmNhZThmNjM=|4e45eb32acba1f080bba177582f5c38822597a4ab96a64e906cca8c3b87a0607\"; _xsrf=2|34e9a513|5bd98113160380829d02d69d0fba51f4|1621183609",
      "Referer": "https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/tut.ipynb",
      "Origin": "https://hub.gke2.mybinder.org",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|34e9a513|5bd98113160380829d02d69d0fba51f4|1621183609",
      "Content-Type": "application/json",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.5",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0",
      "Content-Length": "490",
      "X-Scheme": "https",
      "X-Forwarded-Port": "443,80",
      "X-Forwarded-Host": "hub.gke2.mybinder.org",
      "X-Forwarded-Proto": "https,http",
      "X-Forwarded-For": "117.196.252.225,::ffff:10.0.10.8",
      "X-Real-Ip": "117.196.252.225",
      "X-Request-Id": "1d2334657e06f2c9af5925ac38309a46",
      "Host": "hub.gke2.mybinder.org",
      "Connection": "close"
    }
[E 17:49:40.315 NotebookApp] 500 PUT /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/contents/tut.ipynb (117.196.252.225) 44.340000ms referer=https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/tut.ipynb
[I 17:50:10.925 NotebookApp] Saving file at /tut.ipynb
[E 17:50:10.936 NotebookApp] Error while saving file: tut.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
    Traceback (most recent call last):
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 477, in save
        self._save_notebook(os_path, nb)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 291, in _save_notebook
        nbformat.write(nb, f, version=nbformat.NO_CONVERT)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/__init__.py", line 164, in write
        return write(nb, f, version=version, **kwargs)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/__init__.py", line 107, in writes
        try:
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/validator.py", line 266, in validate
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/words.py", line 20, in generate_corpus_id
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/words.py", line 15, in acceptable_adjectives
    FileNotFoundError: [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[W 17:50:10.936 NotebookApp] 500 PUT /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/contents/tut.ipynb (117.196.252.225): Unexpected error while saving file: tut.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[W 17:50:10.937 NotebookApp] Unexpected error while saving file: tut.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[E 17:50:10.938 NotebookApp] {
      "Cookie": "username-hub-gke2-mybinder-org=\"2|1:0|10:1621183609|30:username-hub-gke2-mybinder-org|44:YWJjYjcwMmU4MGExNDVmMzk3OGI3ZjBlNmNhZThmNjM=|4e45eb32acba1f080bba177582f5c38822597a4ab96a64e906cca8c3b87a0607\"; _xsrf=2|34e9a513|5bd98113160380829d02d69d0fba51f4|1621183609",
      "Referer": "https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/tut.ipynb",
      "Origin": "https://hub.gke2.mybinder.org",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|34e9a513|5bd98113160380829d02d69d0fba51f4|1621183609",
      "Content-Type": "application/json",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.5",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0",
      "Content-Length": "471",
      "X-Scheme": "https",
      "X-Forwarded-Port": "443,80",
      "X-Forwarded-Host": "hub.gke2.mybinder.org",
      "X-Forwarded-Proto": "https,http",
      "X-Forwarded-For": "117.196.252.225,::ffff:10.0.10.8",
      "X-Real-Ip": "117.196.252.225",
      "X-Request-Id": "a40cc065bceba96dc42e4c6bc23ebd12",
      "Host": "hub.gke2.mybinder.org",
      "Connection": "close"
    }
[E 17:50:10.938 NotebookApp] 500 PUT /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/contents/tut.ipynb (117.196.252.225) 13.790000ms referer=https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/tut.ipynb
[I 17:50:11.880 NotebookApp] Saving file at /tut.ipynb
[E 17:50:11.892 NotebookApp] Error while saving file: tut.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
    Traceback (most recent call last):
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 477, in save
        self._save_notebook(os_path, nb)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 291, in _save_notebook
        nbformat.write(nb, f, version=nbformat.NO_CONVERT)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/__init__.py", line 164, in write
        return write(nb, f, version=version, **kwargs)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/__init__.py", line 107, in writes
        try:
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/validator.py", line 266, in validate
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/words.py", line 20, in generate_corpus_id
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/words.py", line 15, in acceptable_adjectives
    FileNotFoundError: [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[W 17:50:11.892 NotebookApp] 500 PUT /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/contents/tut.ipynb (117.196.252.225): Unexpected error while saving file: tut.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[W 17:50:11.893 NotebookApp] Unexpected error while saving file: tut.ipynb [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/nbformat/corpus/adjectives.txt'
[E 17:50:11.894 NotebookApp] {
      "Cookie": "username-hub-gke2-mybinder-org=\"2|1:0|10:1621183609|30:username-hub-gke2-mybinder-org|44:YWJjYjcwMmU4MGExNDVmMzk3OGI3ZjBlNmNhZThmNjM=|4e45eb32acba1f080bba177582f5c38822597a4ab96a64e906cca8c3b87a0607\"; _xsrf=2|34e9a513|5bd98113160380829d02d69d0fba51f4|1621183609",
      "Referer": "https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/tut.ipynb",
      "Origin": "https://hub.gke2.mybinder.org",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|34e9a513|5bd98113160380829d02d69d0fba51f4|1621183609",
      "Content-Type": "application/json",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.5",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0",
      "Content-Length": "490",
      "X-Scheme": "https",
      "X-Forwarded-Port": "443,80",
      "X-Forwarded-Host": "hub.gke2.mybinder.org",
      "X-Forwarded-Proto": "https,http",
      "X-Forwarded-For": "117.196.252.225,::ffff:10.0.10.8",
      "X-Real-Ip": "117.196.252.225",
      "X-Request-Id": "3a2640b9c135a7fd78cdc8fe0eeb6cf1",
      "Host": "hub.gke2.mybinder.org",
      "Connection": "close"
    }
[E 17:50:11.894 NotebookApp] 500 PUT /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/contents/tut.ipynb (117.196.252.225) 14.760000ms referer=https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/tut.ipynb
[I 17:50:24.453 NotebookApp] Starting buffering for 5c93a30c-2907-41f0-bf74-ba433adc3d67:fc2c15d7ec394c3c8a75dd52d37fb3a4
[W 17:50:36.113 NotebookApp] Notebook Matplotlib Exercises .ipynb is not trusted
[I 17:50:37.809 NotebookApp] Kernel started: b52052ef-7638-4d5c-be59-64fdaef1a580, name: python3
[W 17:52:38.571 NotebookApp] Notebook MatplotlibExercises .ipynb is not trusted
[W 17:53:04.943 NotebookApp] 404 GET /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/contents/Matplot.ipynb?type=notebook&content=0&_=1621187558159 (117.196.252.225): No such file or directory: Matplot.ipynb
[W 17:53:04.943 NotebookApp] No such file or directory: Matplot.ipynb
[W 17:53:04.944 NotebookApp] 404 GET /user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/api/contents/Matplot.ipynb?type=notebook&content=0&_=1621187558159 (117.196.252.225) 1.830000ms referer=https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-a8klkqv9/notebooks/MatplotlibExercises%20.ipynb
[I 17:53:06.041 NotebookApp] Uploading file to /Matplot.ipynb
[W 17:53:06.042 NotebookApp] Notebook Matplot.ipynb is not trusted
[I 17:53:09.795 NotebookApp] Saving file at /Matplot.ipynb
[W 17:53:09.796 NotebookApp] Notebook Matplot.ipynb is not trusted
[I 17:53:23.297 NotebookApp] Saving file at /Matplot.ipynb
[W 17:53:23.297 NotebookApp] Notebook Matplot.ipynb is not trusted
[W 2021-05-18 04:50:43.790 LabApp] 'ip' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2021-05-18 04:50:43.790 LabApp] 'port' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2021-05-18 04:50:43.791 LabApp] 'base_url' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2021-05-18 04:50:43.791 LabApp] 'token' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2021-05-18 04:50:43.791 LabApp] 'trust_xheaders' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2021-05-18 04:50:43.791 LabApp] 'allow_origin' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2021-05-18 04:50:43.791 LabApp] 'allow_origin_pat' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2021-05-18 04:50:43.791 LabApp] 'extra_template_paths' was found in both NotebookApp and ServerApp. This is likely a recent change. This config will only be set in NotebookApp. Please check if you should also config these traits in ServerApp for your purpose.
[W 2021-05-18 04:50:43.791 LabApp] 'jinja_template_vars' was found in both NotebookApp and ServerApp. This is likely a recent change. This config will only be set in NotebookApp. Please check if you should also config these traits in ServerApp for your purpose.
[W 2021-05-18 04:50:43.791 LabApp] 'shutdown_no_activity_timeout' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2021-05-18 04:50:43.791 LabApp] 'tornado_settings' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2021-05-18 04:50:43.791 LabApp] 'tornado_settings' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[I 2021-05-18 04:50:43.803 LabApp] JupyterLab extension loaded from /srv/conda/envs/notebook/lib/python3.7/site-packages/jupyterlab
[I 2021-05-18 04:50:43.803 LabApp] JupyterLab application directory is /srv/conda/envs/notebook/share/jupyter/lab
[I 04:50:43.811 NotebookApp] nteract extension loaded from /srv/conda/envs/notebook/lib/python3.7/site-packages/nteract_on_jupyter
[I 04:50:43.813 NotebookApp] Will shut down after 600 seconds with no kernels or terminals.
[I 04:50:43.813 NotebookApp] Serving notebooks from local directory: /home/jovyan
[I 04:50:43.813 NotebookApp] Jupyter Notebook 6.2.0 is running at:
[I 04:50:43.814 NotebookApp] http://jupyter-ra5hid-2dpm-2dnbinteract-2dtutorial-2dlc13dw2a:8888/user/ra5hid-pm-nbinteract-tutorial-lc13dw2a/?token=...
[I 04:50:43.814 NotebookApp]  or http://127.0.0.1:8888/user/ra5hid-pm-nbinteract-tutorial-lc13dw2a/?token=...
[I 04:50:43.814 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 04:50:43.818 NotebookApp] No web browser found: could not locate runnable browser.
[I 04:50:46.356 NotebookApp] 302 GET /user/ra5hid-pm-nbinteract-tutorial-lc13dw2a/ (10.0.5.13) 0.810000ms
[I 04:50:52.135 NotebookApp] 302 GET /user/ra5hid-pm-nbinteract-tutorial-lc13dw2a/?token=4BQfIbCRRSiCvELSEnBgKg (112.133.233.141) 0.780000ms
[I 04:52:49.757 NotebookApp] Kernel started: 6af50547-4a5a-4836-8f42-f4999ec39b6b, name: python3
[I 04:52:49.757 NotebookApp] Culling kernels with idle durations > 600 seconds at 60 second intervals ...
[I 04:52:49.757 NotebookApp] Culling kernels even with connected clients
[I 04:53:15.427 NotebookApp] Saving file at /tut.ipynb
[I 04:53:28.992 NotebookApp] Kernel started: d95a45e3-a1eb-4f43-aba5-fa2a9506d253, name: python3
[I 04:53:34.133 NotebookApp] Starting buffering for d95a45e3-a1eb-4f43-aba5-fa2a9506d253:bd6ca894a7db494f82c327bec1e84761
[I 04:53:35.784 NotebookApp] Starting buffering for 6af50547-4a5a-4836-8f42-f4999ec39b6b:9b506a079cab443296a5c7392211da17
[I 04:53:40.579 NotebookApp] New terminal with automatic name: 1
TermSocket.open: 1
TermSocket.open: Opened 1
[I 04:57:00.721 NotebookApp] Saving file at /Curries.ipynb
[I 04:58:46.313 NotebookApp] Saving file at /Curries.ipynb
[W 05:03:49.759 NotebookApp] Culling 'idle' kernel 'python3' (6af50547-4a5a-4836-8f42-f4999ec39b6b) with 0 connections due to 636 seconds of inactivity.
[I 05:03:49.760 NotebookApp] Kernel shutdown: 6af50547-4a5a-4836-8f42-f4999ec39b6b
[W 05:08:49.759 NotebookApp] Culling 'idle' kernel 'python3' (d95a45e3-a1eb-4f43-aba5-fa2a9506d253) with 1 connections due to 606 seconds of inactivity.
[I 05:08:49.759 NotebookApp] Kernel shutdown: d95a45e3-a1eb-4f43-aba5-fa2a9506d253
[W 05:08:51.170 NotebookApp] 410 DELETE /user/ra5hid-pm-nbinteract-tutorial-lc13dw2a/api/sessions/b45214d7-df7d-4d98-8d36-b2358d425a84 (112.133.233.141): Kernel deleted before session
[W 05:08:51.170 NotebookApp] Kernel deleted before session
[W 05:08:51.171 NotebookApp] 410 DELETE /user/ra5hid-pm-nbinteract-tutorial-lc13dw2a/api/sessions/b45214d7-df7d-4d98-8d36-b2358d425a84 (112.133.233.141) 2.350000ms referer=https://hub.gke2.mybinder.org/user/ra5hid-pm-nbinteract-tutorial-lc13dw2a/notebooks/Curries.ipynb
